# only devguard is allowed to communicate with kratos
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kratos
  namespace: "{{ .Release.Namespace }}"
spec:
    podSelector:
        matchLabels:
            app.kubernetes.io/name: kratos
    policyTypes:
    - Ingress
    ingress:
    - from:
        - podSelector:
            matchLabels:
                app: devguard-api
        - podSelector:
            matchLabels:
                app.kubernetes.io/name: kratos
      ports:
      - protocol: TCP
        port: 4434 # restrict access to the admin port
      - protocol: TCP
        port: 4433 # restrict access to the public port
    - from:
        - podSelector:
            matchLabels:
                app: devguard-web
      ports:
      - protocol: TCP
        port: 4433 # restrict access to the public port
---