# Copyright (C) 2023 Tim Bastin, l3montree UG (haftungsbeschränkt)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
packages:
  github.com/l3montree-dev/devguard/internal/core:
    config:
      recursive: true
      all: true
      filename: "mock_{{.InterfaceName}}.go"
      structname: "{{.InterfaceName | firstUpper}}"
      dir: "mocks"
      pkgname: "mocks"
  github.com/l3montree-dev/devguard/internal/accesscontrol:
    config:
      recursive: true
      all: true
      filename: "mock_{{.InterfaceName}}.go"
      structname: "{{.InterfaceName | firstUpper}}"
      dir: "mocks"
      pkgname: "mocks"
  github.com/l3montree-dev/devguard/cmd/devguard/api:
    config:
      recursive: true
      all: true
      filename: "mock_{{.InterfaceName}}.go"
      structname: "{{.InterfaceName | firstUpper}}"
      dir: "mocks"
      pkgname: "mocks"
  github.com/l3montree-dev/devguard/internal/utils:
    config:
      recursive: true
      all: true
      filename: "mock_{{.InterfaceName}}.go"
      structname: "{{.InterfaceName | firstUpper}}"
      dir: "mocks"
      pkgname: "mocks"
