FROM golang:1.24.2@sha256:d9db32125db0c3a680cfb7a1afcaefb89c898a075ec148fdc2f0f646cc2ed509 AS golang-builder

# set the working directory
WORKDIR /app

ARG TARGETPLATFORM

ENV CRANE_VERSION=v0.19.1
ENV OS=Linux
ENV ARCH=x86_64

RUN curl -sL "https://github.com/google/go-containerregistry/releases/download/${CRANE_VERSION}/go-containerregistry_${OS}_${ARCH}.tar.gz" > go-containerregistry.tar.gz && \
    tar -zxvf go-containerregistry.tar.gz -C /usr/local/bin/ crane

# install trivy   
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.58.1

# install cosign
RUN curl -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64" && mv cosign-linux-amd64 /usr/local/bin/cosign && chmod +x /usr/local/bin/cosign

# install gitleaks
RUN curl -O -L "https://github.com/gitleaks/gitleaks/releases/download/v8.24.2/gitleaks_8.24.2_linux_x64.tar.gz" && \
    tar -zxvf gitleaks_8.24.2_linux_x64.tar.gz -C /usr/local/bin/ gitleaks   

#install unzip
RUN apt-get update && apt-get install -y unzip

# install checkov
RUN curl -sL "https://github.com/bridgecrewio/checkov/releases/download/3.2.403/checkov_linux_X86_64.zip" -o checkov.zip && \
    unzip checkov.zip && \
    mv dist/checkov /usr/local/bin/checkov && \
    chmod +x /usr/local/bin/checkov


COPY . .

# build the scanner
RUN CGO_ENABLED=0 make devguard-scanner
# ----------------------
# create final image with node:alpine
FROM alpine:3.21.3@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c

RUN apk add --no-cache git python3
RUN python3 -m venv /usr/local/bin/venv && \
 /usr/local/bin/venv/bin/pip install --upgrade pip && \
 /usr/local/bin/venv/bin/pip install semgrep

 # add venv bin to path
ENV PATH="/usr/local/bin/venv/bin:$PATH"

COPY --from=golang-builder /app/devguard-scanner /usr/local/bin/devguard-scanner
COPY --from=golang-builder /usr/local/bin/trivy /usr/local/bin/trivy
COPY --from=golang-builder /usr/local/bin/cosign /usr/local/bin/cosign
COPY --from=golang-builder /usr/local/bin/crane /usr/local/bin/crane
COPY --from=golang-builder /usr/local/bin/gitleaks /usr/local/bin/gitleaks
COPY --from=golang-builder /usr/local/bin/checkov /usr/local/bin/checkov

ENTRYPOINT [""]