// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/l3montree-dev/devguard/database/models"
	mock "github.com/stretchr/testify/mock"

	shared "github.com/l3montree-dev/devguard/shared"
)

// AccessControl is an autogenerated mock type for the AccessControl type
type AccessControl struct {
	mock.Mock
}

// AllowRole provides a mock function with given fields: ctx, role, object, action
func (_m *AccessControl) AllowRole(ctx context.Context, role shared.Role, object shared.Object, action []shared.Action) error {
	ret := _m.Called(ctx, role, object, action)

	if len(ret) == 0 {
		panic("no return value specified for AllowRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Role, shared.Object, []shared.Action) error); ok {
		r0 = rf(ctx, role, object, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AllowRoleInAsset provides a mock function with given fields: ctx, asset, role, object, action
func (_m *AccessControl) AllowRoleInAsset(ctx context.Context, asset string, role shared.Role, object shared.Object, action []shared.Action) error {
	ret := _m.Called(ctx, asset, role, object, action)

	if len(ret) == 0 {
		panic("no return value specified for AllowRoleInAsset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, shared.Role, shared.Object, []shared.Action) error); ok {
		r0 = rf(ctx, asset, role, object, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AllowRoleInProject provides a mock function with given fields: ctx, project, role, object, action
func (_m *AccessControl) AllowRoleInProject(ctx context.Context, project string, role shared.Role, object shared.Object, action []shared.Action) error {
	ret := _m.Called(ctx, project, role, object, action)

	if len(ret) == 0 {
		panic("no return value specified for AllowRoleInProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, shared.Role, shared.Object, []shared.Action) error); ok {
		r0 = rf(ctx, project, role, object, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllAssetsForUser provides a mock function with given fields: user
func (_m *AccessControl) GetAllAssetsForUser(user string) ([]string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssetsForUser")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllMembersOfAsset provides a mock function with given fields: projectID
func (_m *AccessControl) GetAllMembersOfAsset(projectID string) ([]string, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMembersOfAsset")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllMembersOfOrganization provides a mock function with no fields
func (_m *AccessControl) GetAllMembersOfOrganization() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllMembersOfOrganization")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllMembersOfProject provides a mock function with given fields: projectID
func (_m *AccessControl) GetAllMembersOfProject(projectID string) ([]string, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMembersOfProject")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllProjectsForUser provides a mock function with given fields: user
func (_m *AccessControl) GetAllProjectsForUser(user string) ([]string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProjectsForUser")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllRoles provides a mock function with given fields: user
func (_m *AccessControl) GetAllRoles(user string) []string {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRoles")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetAssetRole provides a mock function with given fields: user, asset
func (_m *AccessControl) GetAssetRole(user string, asset string) (shared.Role, error) {
	ret := _m.Called(user, asset)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetRole")
	}

	var r0 shared.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (shared.Role, error)); ok {
		return rf(user, asset)
	}
	if rf, ok := ret.Get(0).(func(string, string) shared.Role); ok {
		r0 = rf(user, asset)
	} else {
		r0 = ret.Get(0).(shared.Role)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(user, asset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDomainRole provides a mock function with given fields: user
func (_m *AccessControl) GetDomainRole(user string) (shared.Role, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GetDomainRole")
	}

	var r0 shared.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (shared.Role, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(string) shared.Role); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(shared.Role)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExternalEntityProviderID provides a mock function with no fields
func (_m *AccessControl) GetExternalEntityProviderID() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExternalEntityProviderID")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// GetOwnerOfOrganization provides a mock function with no fields
func (_m *AccessControl) GetOwnerOfOrganization() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOwnerOfOrganization")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProjectRole provides a mock function with given fields: user, project
func (_m *AccessControl) GetProjectRole(user string, project string) (shared.Role, error) {
	ret := _m.Called(user, project)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectRole")
	}

	var r0 shared.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (shared.Role, error)); ok {
		return rf(user, project)
	}
	if rf, ok := ret.Get(0).(func(string, string) shared.Role); ok {
		r0 = rf(user, project)
	} else {
		r0 = ret.Get(0).(shared.Role)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(user, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GrantRole provides a mock function with given fields: ctx, subject, role
func (_m *AccessControl) GrantRole(ctx context.Context, subject string, role shared.Role) error {
	ret := _m.Called(ctx, subject, role)

	if len(ret) == 0 {
		panic("no return value specified for GrantRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, shared.Role) error); ok {
		r0 = rf(ctx, subject, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GrantRoleInAsset provides a mock function with given fields: ctx, subject, role, asset
func (_m *AccessControl) GrantRoleInAsset(ctx context.Context, subject string, role shared.Role, asset string) error {
	ret := _m.Called(ctx, subject, role, asset)

	if len(ret) == 0 {
		panic("no return value specified for GrantRoleInAsset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, shared.Role, string) error); ok {
		r0 = rf(ctx, subject, role, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GrantRoleInProject provides a mock function with given fields: ctx, subject, role, project
func (_m *AccessControl) GrantRoleInProject(ctx context.Context, subject string, role shared.Role, project string) error {
	ret := _m.Called(ctx, subject, role, project)

	if len(ret) == 0 {
		panic("no return value specified for GrantRoleInProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, shared.Role, string) error); ok {
		r0 = rf(ctx, subject, role, project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasAccess provides a mock function with given fields: ctx, subject
func (_m *AccessControl) HasAccess(ctx context.Context, subject string) (bool, error) {
	ret := _m.Called(ctx, subject)

	if len(ret) == 0 {
		panic("no return value specified for HasAccess")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, subject)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, subject)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InheritAssetRole provides a mock function with given fields: ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions, asset
func (_m *AccessControl) InheritAssetRole(ctx context.Context, roleWhichGetsPermissions shared.Role, roleWhichProvidesPermissions shared.Role, asset string) error {
	ret := _m.Called(ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions, asset)

	if len(ret) == 0 {
		panic("no return value specified for InheritAssetRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Role, shared.Role, string) error); ok {
		r0 = rf(ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InheritProjectRole provides a mock function with given fields: ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions, project
func (_m *AccessControl) InheritProjectRole(ctx context.Context, roleWhichGetsPermissions shared.Role, roleWhichProvidesPermissions shared.Role, project string) error {
	ret := _m.Called(ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions, project)

	if len(ret) == 0 {
		panic("no return value specified for InheritProjectRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Role, shared.Role, string) error); ok {
		r0 = rf(ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions, project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InheritProjectRolesAcrossProjects provides a mock function with given fields: ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions
func (_m *AccessControl) InheritProjectRolesAcrossProjects(ctx context.Context, roleWhichGetsPermissions shared.ProjectRole, roleWhichProvidesPermissions shared.ProjectRole) error {
	ret := _m.Called(ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions)

	if len(ret) == 0 {
		panic("no return value specified for InheritProjectRolesAcrossProjects")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.ProjectRole, shared.ProjectRole) error); ok {
		r0 = rf(ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InheritRole provides a mock function with given fields: ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions
func (_m *AccessControl) InheritRole(ctx context.Context, roleWhichGetsPermissions shared.Role, roleWhichProvidesPermissions shared.Role) error {
	ret := _m.Called(ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions)

	if len(ret) == 0 {
		panic("no return value specified for InheritRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Role, shared.Role) error); ok {
		r0 = rf(ctx, roleWhichGetsPermissions, roleWhichProvidesPermissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsAllowed provides a mock function with given fields: ctx, subject, object, action
func (_m *AccessControl) IsAllowed(ctx context.Context, subject string, object shared.Object, action shared.Action) (bool, error) {
	ret := _m.Called(ctx, subject, object, action)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, shared.Object, shared.Action) (bool, error)); ok {
		return rf(ctx, subject, object, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, shared.Object, shared.Action) bool); ok {
		r0 = rf(ctx, subject, object, action)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, shared.Object, shared.Action) error); ok {
		r1 = rf(ctx, subject, object, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsAllowedInAsset provides a mock function with given fields: ctx, asset, user, object, action
func (_m *AccessControl) IsAllowedInAsset(ctx context.Context, asset *models.Asset, user string, object shared.Object, action shared.Action) (bool, error) {
	ret := _m.Called(ctx, asset, user, object, action)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowedInAsset")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Asset, string, shared.Object, shared.Action) (bool, error)); ok {
		return rf(ctx, asset, user, object, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Asset, string, shared.Object, shared.Action) bool); ok {
		r0 = rf(ctx, asset, user, object, action)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Asset, string, shared.Object, shared.Action) error); ok {
		r1 = rf(ctx, asset, user, object, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsAllowedInProject provides a mock function with given fields: ctx, project, user, object, action
func (_m *AccessControl) IsAllowedInProject(ctx context.Context, project *models.Project, user string, object shared.Object, action shared.Action) (bool, error) {
	ret := _m.Called(ctx, project, user, object, action)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowedInProject")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Project, string, shared.Object, shared.Action) (bool, error)); ok {
		return rf(ctx, project, user, object, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Project, string, shared.Object, shared.Action) bool); ok {
		r0 = rf(ctx, project, user, object, action)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Project, string, shared.Object, shared.Action) error); ok {
		r1 = rf(ctx, project, user, object, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkDomainAndProjectRole provides a mock function with given fields: ctx, domainRoleWhichGetsPermission, projectRoleWhichProvidesPermissions, project
func (_m *AccessControl) LinkDomainAndProjectRole(ctx context.Context, domainRoleWhichGetsPermission shared.Role, projectRoleWhichProvidesPermissions shared.Role, project string) error {
	ret := _m.Called(ctx, domainRoleWhichGetsPermission, projectRoleWhichProvidesPermissions, project)

	if len(ret) == 0 {
		panic("no return value specified for LinkDomainAndProjectRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Role, shared.Role, string) error); ok {
		r0 = rf(ctx, domainRoleWhichGetsPermission, projectRoleWhichProvidesPermissions, project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkProjectAndAssetRole provides a mock function with given fields: ctx, projectRoleWhichGetsPermission, assetRoleWhichProvidesPermissions, project, asset
func (_m *AccessControl) LinkProjectAndAssetRole(ctx context.Context, projectRoleWhichGetsPermission shared.Role, assetRoleWhichProvidesPermissions shared.Role, project string, asset string) error {
	ret := _m.Called(ctx, projectRoleWhichGetsPermission, assetRoleWhichProvidesPermissions, project, asset)

	if len(ret) == 0 {
		panic("no return value specified for LinkProjectAndAssetRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Role, shared.Role, string, string) error); ok {
		r0 = rf(ctx, projectRoleWhichGetsPermission, assetRoleWhichProvidesPermissions, project, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeAllRolesInAssetForUser provides a mock function with given fields: ctx, user, asset
func (_m *AccessControl) RevokeAllRolesInAssetForUser(ctx context.Context, user string, asset string) error {
	ret := _m.Called(ctx, user, asset)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllRolesInAssetForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, user, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeAllRolesInProjectForUser provides a mock function with given fields: ctx, user, project
func (_m *AccessControl) RevokeAllRolesInProjectForUser(ctx context.Context, user string, project string) error {
	ret := _m.Called(ctx, user, project)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllRolesInProjectForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, user, project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeRole provides a mock function with given fields: ctx, subject, role
func (_m *AccessControl) RevokeRole(ctx context.Context, subject string, role shared.Role) error {
	ret := _m.Called(ctx, subject, role)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, shared.Role) error); ok {
		r0 = rf(ctx, subject, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeRoleInAsset provides a mock function with given fields: ctx, subject, role, asset
func (_m *AccessControl) RevokeRoleInAsset(ctx context.Context, subject string, role shared.Role, asset string) error {
	ret := _m.Called(ctx, subject, role, asset)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRoleInAsset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, shared.Role, string) error); ok {
		r0 = rf(ctx, subject, role, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeRoleInProject provides a mock function with given fields: ctx, subject, role, project
func (_m *AccessControl) RevokeRoleInProject(ctx context.Context, subject string, role shared.Role, project string) error {
	ret := _m.Called(ctx, subject, role, project)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRoleInProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, shared.Role, string) error); ok {
		r0 = rf(ctx, subject, role, project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAccessControl creates a new instance of AccessControl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccessControl(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccessControl {
	mock := &AccessControl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
