// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	models "github.com/l3montree-dev/devguard/database/models"

	uuid "github.com/google/uuid"
)

// AssetVersionRepository is an autogenerated mock type for the AssetVersionRepository type
type AssetVersionRepository struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx, tx
func (_m *AssetVersionRepository) All(ctx context.Context, tx *gorm.DB) ([]models.AssetVersion, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []models.AssetVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]models.AssetVersion, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []models.AssetVersion); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AssetVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Begin provides a mock function with given fields: ctx
func (_m *AssetVersionRepository) Begin(ctx context.Context) *gorm.DB {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, assetVersion
func (_m *AssetVersionRepository) Delete(ctx context.Context, tx *gorm.DB, assetVersion *models.AssetVersion) error {
	ret := _m.Called(ctx, tx, assetVersion)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.AssetVersion) error); ok {
		r0 = rf(ctx, tx, assetVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOldAssetVersions provides a mock function with given fields: ctx, tx, day
func (_m *AssetVersionRepository) DeleteOldAssetVersions(ctx context.Context, tx *gorm.DB, day int) (int64, error) {
	ret := _m.Called(ctx, tx, day)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldAssetVersions")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int) (int64, error)); ok {
		return rf(ctx, tx, day)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int) int64); ok {
		r0 = rf(ctx, tx, day)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, int) error); ok {
		r1 = rf(ctx, tx, day)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteOldAssetVersionsOfAsset provides a mock function with given fields: ctx, tx, assetID, day
func (_m *AssetVersionRepository) DeleteOldAssetVersionsOfAsset(ctx context.Context, tx *gorm.DB, assetID uuid.UUID, day int) (int64, error) {
	ret := _m.Called(ctx, tx, assetID, day)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldAssetVersionsOfAsset")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, int) (int64, error)); ok {
		return rf(ctx, tx, assetID, day)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, int) int64); ok {
		r0 = rf(ctx, tx, assetID, day)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, int) error); ok {
		r1 = rf(ctx, tx, assetID, day)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOrCreate provides a mock function with given fields: ctx, tx, assetVersionName, assetID, tag, defaultBranchName
func (_m *AssetVersionRepository) FindOrCreate(ctx context.Context, tx *gorm.DB, assetVersionName string, assetID uuid.UUID, tag bool, defaultBranchName *string) (models.AssetVersion, error) {
	ret := _m.Called(ctx, tx, assetVersionName, assetID, tag, defaultBranchName)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreate")
	}

	var r0 models.AssetVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string, uuid.UUID, bool, *string) (models.AssetVersion, error)); ok {
		return rf(ctx, tx, assetVersionName, assetID, tag, defaultBranchName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string, uuid.UUID, bool, *string) models.AssetVersion); ok {
		r0 = rf(ctx, tx, assetVersionName, assetID, tag, defaultBranchName)
	} else {
		r0 = ret.Get(0).(models.AssetVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string, uuid.UUID, bool, *string) error); ok {
		r1 = rf(ctx, tx, assetVersionName, assetID, tag, defaultBranchName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllTagsAndDefaultBranchForAsset provides a mock function with given fields: ctx, tx, assetID
func (_m *AssetVersionRepository) GetAllTagsAndDefaultBranchForAsset(ctx context.Context, tx *gorm.DB, assetID uuid.UUID) ([]models.AssetVersion, error) {
	ret := _m.Called(ctx, tx, assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTagsAndDefaultBranchForAsset")
	}

	var r0 []models.AssetVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]models.AssetVersion, error)); ok {
		return rf(ctx, tx, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []models.AssetVersion); ok {
		r0 = rf(ctx, tx, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AssetVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAmountOfAssetVersionsInOrg provides a mock function with given fields: ctx, tx, orgID
func (_m *AssetVersionRepository) GetAmountOfAssetVersionsInOrg(ctx context.Context, tx *gorm.DB, orgID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, tx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetAmountOfAssetVersionsInOrg")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (int, error)); ok {
		return rf(ctx, tx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) int); ok {
		r0 = rf(ctx, tx, orgID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAssetVersionsByAssetID provides a mock function with given fields: ctx, tx, assetID
func (_m *AssetVersionRepository) GetAssetVersionsByAssetID(ctx context.Context, tx *gorm.DB, assetID uuid.UUID) ([]models.AssetVersion, error) {
	ret := _m.Called(ctx, tx, assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetVersionsByAssetID")
	}

	var r0 []models.AssetVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]models.AssetVersion, error)); ok {
		return rf(ctx, tx, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []models.AssetVersion); ok {
		r0 = rf(ctx, tx, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AssetVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAssetVersionsByAssetIDWithArtifacts provides a mock function with given fields: ctx, tx, assetID
func (_m *AssetVersionRepository) GetAssetVersionsByAssetIDWithArtifacts(ctx context.Context, tx *gorm.DB, assetID uuid.UUID) ([]models.AssetVersion, error) {
	ret := _m.Called(ctx, tx, assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetVersionsByAssetIDWithArtifacts")
	}

	var r0 []models.AssetVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]models.AssetVersion, error)); ok {
		return rf(ctx, tx, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []models.AssetVersion); ok {
		r0 = rf(ctx, tx, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AssetVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDB provides a mock function with given fields: ctx, tx
func (_m *AssetVersionRepository) GetDB(ctx context.Context, tx *gorm.DB) *gorm.DB {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) *gorm.DB); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// GetDefaultAssetVersion provides a mock function with given fields: ctx, tx, assetID
func (_m *AssetVersionRepository) GetDefaultAssetVersion(ctx context.Context, tx *gorm.DB, assetID uuid.UUID) (models.AssetVersion, error) {
	ret := _m.Called(ctx, tx, assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultAssetVersion")
	}

	var r0 models.AssetVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) (models.AssetVersion, error)); ok {
		return rf(ctx, tx, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) models.AssetVersion); ok {
		r0 = rf(ctx, tx, assetID)
	} else {
		r0 = ret.Get(0).(models.AssetVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDefaultAssetVersionsByProjectID provides a mock function with given fields: ctx, tx, projectID
func (_m *AssetVersionRepository) GetDefaultAssetVersionsByProjectID(ctx context.Context, tx *gorm.DB, projectID uuid.UUID) ([]models.AssetVersion, error) {
	ret := _m.Called(ctx, tx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultAssetVersionsByProjectID")
	}

	var r0 []models.AssetVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) ([]models.AssetVersion, error)); ok {
		return rf(ctx, tx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID) []models.AssetVersion); ok {
		r0 = rf(ctx, tx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AssetVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDefaultAssetVersionsByProjectIDs provides a mock function with given fields: ctx, tx, projectIDs
func (_m *AssetVersionRepository) GetDefaultAssetVersionsByProjectIDs(ctx context.Context, tx *gorm.DB, projectIDs []uuid.UUID) ([]models.AssetVersion, error) {
	ret := _m.Called(ctx, tx, projectIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultAssetVersionsByProjectIDs")
	}

	var r0 []models.AssetVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []uuid.UUID) ([]models.AssetVersion, error)); ok {
		return rf(ctx, tx, projectIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []uuid.UUID) []models.AssetVersion); ok {
		r0 = rf(ctx, tx, projectIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AssetVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, []uuid.UUID) error); ok {
		r1 = rf(ctx, tx, projectIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: ctx, tx, assetVersionName, assetID
func (_m *AssetVersionRepository) Read(ctx context.Context, tx *gorm.DB, assetVersionName string, assetID uuid.UUID) (models.AssetVersion, error) {
	ret := _m.Called(ctx, tx, assetVersionName, assetID)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 models.AssetVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string, uuid.UUID) (models.AssetVersion, error)); ok {
		return rf(ctx, tx, assetVersionName, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string, uuid.UUID) models.AssetVersion); ok {
		r0 = rf(ctx, tx, assetVersionName, assetID)
	} else {
		r0 = ret.Get(0).(models.AssetVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, assetVersionName, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadBySlug provides a mock function with given fields: ctx, tx, assetID, slug
func (_m *AssetVersionRepository) ReadBySlug(ctx context.Context, tx *gorm.DB, assetID uuid.UUID, slug string) (models.AssetVersion, error) {
	ret := _m.Called(ctx, tx, assetID, slug)

	if len(ret) == 0 {
		panic("no return value specified for ReadBySlug")
	}

	var r0 models.AssetVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, string) (models.AssetVersion, error)); ok {
		return rf(ctx, tx, assetID, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, string) models.AssetVersion); ok {
		r0 = rf(ctx, tx, assetID, slug)
	} else {
		r0 = ret.Get(0).(models.AssetVersion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tx, assetID, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, tx, assetVersion
func (_m *AssetVersionRepository) Save(ctx context.Context, tx *gorm.DB, assetVersion *models.AssetVersion) error {
	ret := _m.Called(ctx, tx, assetVersion)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.AssetVersion) error); ok {
		r0 = rf(ctx, tx, assetVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAssetDefaultBranch provides a mock function with given fields: ctx, tx, assetID, defaultBranch
func (_m *AssetVersionRepository) UpdateAssetDefaultBranch(ctx context.Context, tx *gorm.DB, assetID uuid.UUID, defaultBranch string) error {
	ret := _m.Called(ctx, tx, assetID, defaultBranch)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAssetDefaultBranch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, uuid.UUID, string) error); ok {
		r0 = rf(ctx, tx, assetID, defaultBranch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAssetVersionRepository creates a new instance of AssetVersionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssetVersionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssetVersionRepository {
	mock := &AssetVersionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
