// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	clause "gorm.io/gorm/clause"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	models "github.com/l3montree-dev/devguard/database/models"
)

// ComponentProjectRepository is an autogenerated mock type for the ComponentProjectRepository type
type ComponentProjectRepository struct {
	mock.Mock
}

// Activate provides a mock function with given fields: ctx, tx, id
func (_m *ComponentProjectRepository) Activate(ctx context.Context, tx *gorm.DB, id string) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// All provides a mock function with given fields: ctx, tx
func (_m *ComponentProjectRepository) All(ctx context.Context, tx *gorm.DB) ([]models.ComponentProject, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []models.ComponentProject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]models.ComponentProject, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []models.ComponentProject); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ComponentProject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Begin provides a mock function with given fields: ctx
func (_m *ComponentProjectRepository) Begin(ctx context.Context) *gorm.DB {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// CleanupOrphanedRecords provides a mock function with given fields: ctx
func (_m *ComponentProjectRepository) CleanupOrphanedRecords(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOrphanedRecords")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, tx, t
func (_m *ComponentProjectRepository) Create(ctx context.Context, tx *gorm.DB, t *models.ComponentProject) error {
	ret := _m.Called(ctx, tx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.ComponentProject) error); ok {
		r0 = rf(ctx, tx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBatch provides a mock function with given fields: ctx, tx, ts
func (_m *ComponentProjectRepository) CreateBatch(ctx context.Context, tx *gorm.DB, ts []models.ComponentProject) error {
	ret := _m.Called(ctx, tx, ts)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []models.ComponentProject) error); ok {
		r0 = rf(ctx, tx, ts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, tx, id
func (_m *ComponentProjectRepository) Delete(ctx context.Context, tx *gorm.DB, id string) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBatch provides a mock function with given fields: ctx, tx, ids
func (_m *ComponentProjectRepository) DeleteBatch(ctx context.Context, tx *gorm.DB, ids []models.ComponentProject) error {
	ret := _m.Called(ctx, tx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []models.ComponentProject) error); ok {
		r0 = rf(ctx, tx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllOutdatedProjects provides a mock function with given fields: ctx, tx
func (_m *ComponentProjectRepository) FindAllOutdatedProjects(ctx context.Context, tx *gorm.DB) ([]models.ComponentProject, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllOutdatedProjects")
	}

	var r0 []models.ComponentProject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) ([]models.ComponentProject, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) []models.ComponentProject); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ComponentProject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDB provides a mock function with given fields: ctx, tx
func (_m *ComponentProjectRepository) GetDB(ctx context.Context, tx *gorm.DB) *gorm.DB {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) *gorm.DB); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// List provides a mock function with given fields: ctx, tx, ids
func (_m *ComponentProjectRepository) List(ctx context.Context, tx *gorm.DB, ids []string) ([]models.ComponentProject, error) {
	ret := _m.Called(ctx, tx, ids)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.ComponentProject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []string) ([]models.ComponentProject, error)); ok {
		return rf(ctx, tx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []string) []models.ComponentProject); ok {
		r0 = rf(ctx, tx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ComponentProject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, []string) error); ok {
		r1 = rf(ctx, tx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: ctx, tx, id
func (_m *ComponentProjectRepository) Read(ctx context.Context, tx *gorm.DB, id string) (models.ComponentProject, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 models.ComponentProject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (models.ComponentProject, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) models.ComponentProject); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(models.ComponentProject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, tx, t
func (_m *ComponentProjectRepository) Save(ctx context.Context, tx *gorm.DB, t *models.ComponentProject) error {
	ret := _m.Called(ctx, tx, t)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.ComponentProject) error); ok {
		r0 = rf(ctx, tx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveBatch provides a mock function with given fields: ctx, tx, ts
func (_m *ComponentProjectRepository) SaveBatch(ctx context.Context, tx *gorm.DB, ts []models.ComponentProject) error {
	ret := _m.Called(ctx, tx, ts)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []models.ComponentProject) error); ok {
		r0 = rf(ctx, tx, ts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveBatchBestEffort provides a mock function with given fields: ctx, tx, ts
func (_m *ComponentProjectRepository) SaveBatchBestEffort(ctx context.Context, tx *gorm.DB, ts []models.ComponentProject) error {
	ret := _m.Called(ctx, tx, ts)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatchBestEffort")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []models.ComponentProject) error); ok {
		r0 = rf(ctx, tx, ts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transaction provides a mock function with given fields: ctx, fn
func (_m *ComponentProjectRepository) Transaction(ctx context.Context, fn func(*gorm.DB) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(*gorm.DB) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: ctx, tx, t, conflictingColumns, updateOnly
func (_m *ComponentProjectRepository) Upsert(ctx context.Context, tx *gorm.DB, t *[]*models.ComponentProject, conflictingColumns []clause.Column, updateOnly []string) error {
	ret := _m.Called(ctx, tx, t, conflictingColumns, updateOnly)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *[]*models.ComponentProject, []clause.Column, []string) error); ok {
		r0 = rf(ctx, tx, t, conflictingColumns, updateOnly)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewComponentProjectRepository creates a new instance of ComponentProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComponentProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ComponentProjectRepository {
	mock := &ComponentProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
