// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExternalPropertyFileReference is an autogenerated mock type for the ExternalPropertyFileReference type
type ExternalPropertyFileReference struct {
	mock.Mock
}

// NewExternalPropertyFileReference creates a new instance of ExternalPropertyFileReference. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExternalPropertyFileReference(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExternalPropertyFileReference {
	mock := &ExternalPropertyFileReference{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
