// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LeaderelectionConfigService is an autogenerated mock type for the configService type
type LeaderelectionConfigService struct {
	mock.Mock
}

type LeaderelectionConfigService_Expecter struct {
	mock *mock.Mock
}

func (_m *LeaderelectionConfigService) EXPECT() *LeaderelectionConfigService_Expecter {
	return &LeaderelectionConfigService_Expecter{mock: &_m.Mock}
}

// GetJSONConfig provides a mock function with given fields: key, v
func (_m *LeaderelectionConfigService) GetJSONConfig(key string, v any) error {
	ret := _m.Called(key, v)

	if len(ret) == 0 {
		panic("no return value specified for GetJSONConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = rf(key, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LeaderelectionConfigService_GetJSONConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJSONConfig'
type LeaderelectionConfigService_GetJSONConfig_Call struct {
	*mock.Call
}

// GetJSONConfig is a helper method to define mock.On call
//   - key string
//   - v any
func (_e *LeaderelectionConfigService_Expecter) GetJSONConfig(key interface{}, v interface{}) *LeaderelectionConfigService_GetJSONConfig_Call {
	return &LeaderelectionConfigService_GetJSONConfig_Call{Call: _e.mock.On("GetJSONConfig", key, v)}
}

func (_c *LeaderelectionConfigService_GetJSONConfig_Call) Run(run func(key string, v any)) *LeaderelectionConfigService_GetJSONConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any))
	})
	return _c
}

func (_c *LeaderelectionConfigService_GetJSONConfig_Call) Return(_a0 error) *LeaderelectionConfigService_GetJSONConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LeaderelectionConfigService_GetJSONConfig_Call) RunAndReturn(run func(string, any) error) *LeaderelectionConfigService_GetJSONConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SetJSONConfig provides a mock function with given fields: key, v
func (_m *LeaderelectionConfigService) SetJSONConfig(key string, v any) error {
	ret := _m.Called(key, v)

	if len(ret) == 0 {
		panic("no return value specified for SetJSONConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = rf(key, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LeaderelectionConfigService_SetJSONConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetJSONConfig'
type LeaderelectionConfigService_SetJSONConfig_Call struct {
	*mock.Call
}

// SetJSONConfig is a helper method to define mock.On call
//   - key string
//   - v any
func (_e *LeaderelectionConfigService_Expecter) SetJSONConfig(key interface{}, v interface{}) *LeaderelectionConfigService_SetJSONConfig_Call {
	return &LeaderelectionConfigService_SetJSONConfig_Call{Call: _e.mock.On("SetJSONConfig", key, v)}
}

func (_c *LeaderelectionConfigService_SetJSONConfig_Call) Run(run func(key string, v any)) *LeaderelectionConfigService_SetJSONConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any))
	})
	return _c
}

func (_c *LeaderelectionConfigService_SetJSONConfig_Call) Return(_a0 error) *LeaderelectionConfigService_SetJSONConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LeaderelectionConfigService_SetJSONConfig_Call) RunAndReturn(run func(string, any) error) *LeaderelectionConfigService_SetJSONConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewLeaderelectionConfigService creates a new instance of LeaderelectionConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaderelectionConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaderelectionConfigService {
	mock := &LeaderelectionConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
