// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	"github.com/l3montree-dev/devguard/shared"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthorizer creates a new instance of Authorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authorizer {
	mock := &Authorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Authorizer is an autogenerated mock type for the Authorizer type
type Authorizer struct {
	mock.Mock
}

type Authorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *Authorizer) EXPECT() *Authorizer_Expecter {
	return &Authorizer_Expecter{mock: &_m.Mock}
}

// IsAllowedInAsset provides a mock function for the type Authorizer
func (_mock *Authorizer) IsAllowedInAsset(ctx shared.Context, session shared.AuthSession, obj shared.Object, act shared.Action) (bool, error) {
	ret := _mock.Called(ctx, session, obj, act)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowedInAsset")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(shared.Context, shared.AuthSession, shared.Object, shared.Action) (bool, error)); ok {
		return returnFunc(ctx, session, obj, act)
	}
	if returnFunc, ok := ret.Get(0).(func(shared.Context, shared.AuthSession, shared.Object, shared.Action) bool); ok {
		r0 = returnFunc(ctx, session, obj, act)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(shared.Context, shared.AuthSession, shared.Object, shared.Action) error); ok {
		r1 = returnFunc(ctx, session, obj, act)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Authorizer_IsAllowedInAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowedInAsset'
type Authorizer_IsAllowedInAsset_Call struct {
	*mock.Call
}

// IsAllowedInAsset is a helper method to define mock.On call
//   - ctx shared.Context
//   - session shared.AuthSession
//   - obj shared.Object
//   - act shared.Action
func (_e *Authorizer_Expecter) IsAllowedInAsset(ctx interface{}, session interface{}, obj interface{}, act interface{}) *Authorizer_IsAllowedInAsset_Call {
	return &Authorizer_IsAllowedInAsset_Call{Call: _e.mock.On("IsAllowedInAsset", ctx, session, obj, act)}
}

func (_c *Authorizer_IsAllowedInAsset_Call) Run(run func(ctx shared.Context, session shared.AuthSession, obj shared.Object, act shared.Action)) *Authorizer_IsAllowedInAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 shared.Context
		if args[0] != nil {
			arg0 = args[0].(shared.Context)
		}
		var arg1 shared.AuthSession
		if args[1] != nil {
			arg1 = args[1].(shared.AuthSession)
		}
		var arg2 shared.Object
		if args[2] != nil {
			arg2 = args[2].(shared.Object)
		}
		var arg3 shared.Action
		if args[3] != nil {
			arg3 = args[3].(shared.Action)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Authorizer_IsAllowedInAsset_Call) Return(b bool, err error) *Authorizer_IsAllowedInAsset_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Authorizer_IsAllowedInAsset_Call) RunAndReturn(run func(ctx shared.Context, session shared.AuthSession, obj shared.Object, act shared.Action) (bool, error)) *Authorizer_IsAllowedInAsset_Call {
	_c.Call.Return(run)
	return _c
}

// IsAllowedInOrg provides a mock function for the type Authorizer
func (_mock *Authorizer) IsAllowedInOrg(ctx shared.Context, session shared.AuthSession, obj shared.Object, act shared.Action) (bool, error) {
	ret := _mock.Called(ctx, session, obj, act)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowedInOrg")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(shared.Context, shared.AuthSession, shared.Object, shared.Action) (bool, error)); ok {
		return returnFunc(ctx, session, obj, act)
	}
	if returnFunc, ok := ret.Get(0).(func(shared.Context, shared.AuthSession, shared.Object, shared.Action) bool); ok {
		r0 = returnFunc(ctx, session, obj, act)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(shared.Context, shared.AuthSession, shared.Object, shared.Action) error); ok {
		r1 = returnFunc(ctx, session, obj, act)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Authorizer_IsAllowedInOrg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowedInOrg'
type Authorizer_IsAllowedInOrg_Call struct {
	*mock.Call
}

// IsAllowedInOrg is a helper method to define mock.On call
//   - ctx shared.Context
//   - session shared.AuthSession
//   - obj shared.Object
//   - act shared.Action
func (_e *Authorizer_Expecter) IsAllowedInOrg(ctx interface{}, session interface{}, obj interface{}, act interface{}) *Authorizer_IsAllowedInOrg_Call {
	return &Authorizer_IsAllowedInOrg_Call{Call: _e.mock.On("IsAllowedInOrg", ctx, session, obj, act)}
}

func (_c *Authorizer_IsAllowedInOrg_Call) Run(run func(ctx shared.Context, session shared.AuthSession, obj shared.Object, act shared.Action)) *Authorizer_IsAllowedInOrg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 shared.Context
		if args[0] != nil {
			arg0 = args[0].(shared.Context)
		}
		var arg1 shared.AuthSession
		if args[1] != nil {
			arg1 = args[1].(shared.AuthSession)
		}
		var arg2 shared.Object
		if args[2] != nil {
			arg2 = args[2].(shared.Object)
		}
		var arg3 shared.Action
		if args[3] != nil {
			arg3 = args[3].(shared.Action)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Authorizer_IsAllowedInOrg_Call) Return(b bool, err error) *Authorizer_IsAllowedInOrg_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Authorizer_IsAllowedInOrg_Call) RunAndReturn(run func(ctx shared.Context, session shared.AuthSession, obj shared.Object, act shared.Action) (bool, error)) *Authorizer_IsAllowedInOrg_Call {
	_c.Call.Return(run)
	return _c
}

// IsAllowedInProject provides a mock function for the type Authorizer
func (_mock *Authorizer) IsAllowedInProject(ctx shared.Context, session shared.AuthSession, obj shared.Object, act shared.Action) (bool, error) {
	ret := _mock.Called(ctx, session, obj, act)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowedInProject")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(shared.Context, shared.AuthSession, shared.Object, shared.Action) (bool, error)); ok {
		return returnFunc(ctx, session, obj, act)
	}
	if returnFunc, ok := ret.Get(0).(func(shared.Context, shared.AuthSession, shared.Object, shared.Action) bool); ok {
		r0 = returnFunc(ctx, session, obj, act)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(shared.Context, shared.AuthSession, shared.Object, shared.Action) error); ok {
		r1 = returnFunc(ctx, session, obj, act)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Authorizer_IsAllowedInProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowedInProject'
type Authorizer_IsAllowedInProject_Call struct {
	*mock.Call
}

// IsAllowedInProject is a helper method to define mock.On call
//   - ctx shared.Context
//   - session shared.AuthSession
//   - obj shared.Object
//   - act shared.Action
func (_e *Authorizer_Expecter) IsAllowedInProject(ctx interface{}, session interface{}, obj interface{}, act interface{}) *Authorizer_IsAllowedInProject_Call {
	return &Authorizer_IsAllowedInProject_Call{Call: _e.mock.On("IsAllowedInProject", ctx, session, obj, act)}
}

func (_c *Authorizer_IsAllowedInProject_Call) Run(run func(ctx shared.Context, session shared.AuthSession, obj shared.Object, act shared.Action)) *Authorizer_IsAllowedInProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 shared.Context
		if args[0] != nil {
			arg0 = args[0].(shared.Context)
		}
		var arg1 shared.AuthSession
		if args[1] != nil {
			arg1 = args[1].(shared.AuthSession)
		}
		var arg2 shared.Object
		if args[2] != nil {
			arg2 = args[2].(shared.Object)
		}
		var arg3 shared.Action
		if args[3] != nil {
			arg3 = args[3].(shared.Action)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Authorizer_IsAllowedInProject_Call) Return(b bool, err error) *Authorizer_IsAllowedInProject_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Authorizer_IsAllowedInProject_Call) RunAndReturn(run func(ctx shared.Context, session shared.AuthSession, obj shared.Object, act shared.Action) (bool, error)) *Authorizer_IsAllowedInProject_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAPIToken provides a mock function for the type Authorizer
func (_mock *Authorizer) VerifyAPIToken(ctx context.Context, token string) (string, string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAPIToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Authorizer_VerifyAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAPIToken'
type Authorizer_VerifyAPIToken_Call struct {
	*mock.Call
}

// VerifyAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Authorizer_Expecter) VerifyAPIToken(ctx interface{}, token interface{}) *Authorizer_VerifyAPIToken_Call {
	return &Authorizer_VerifyAPIToken_Call{Call: _e.mock.On("VerifyAPIToken", ctx, token)}
}

func (_c *Authorizer_VerifyAPIToken_Call) Run(run func(ctx context.Context, token string)) *Authorizer_VerifyAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Authorizer_VerifyAPIToken_Call) Return(s string, s1 string, err error) *Authorizer_VerifyAPIToken_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *Authorizer_VerifyAPIToken_Call) RunAndReturn(run func(ctx context.Context, token string) (string, string, error)) *Authorizer_VerifyAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAdminRequest provides a mock function for the type Authorizer
func (_mock *Authorizer) VerifyAdminRequest(req *http.Request) (bool, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAdminRequest")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (bool, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) bool); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Authorizer_VerifyAdminRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAdminRequest'
type Authorizer_VerifyAdminRequest_Call struct {
	*mock.Call
}

// VerifyAdminRequest is a helper method to define mock.On call
//   - req *http.Request
func (_e *Authorizer_Expecter) VerifyAdminRequest(req interface{}) *Authorizer_VerifyAdminRequest_Call {
	return &Authorizer_VerifyAdminRequest_Call{Call: _e.mock.On("VerifyAdminRequest", req)}
}

func (_c *Authorizer_VerifyAdminRequest_Call) Run(run func(req *http.Request)) *Authorizer_VerifyAdminRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Authorizer_VerifyAdminRequest_Call) Return(b bool, err error) *Authorizer_VerifyAdminRequest_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Authorizer_VerifyAdminRequest_Call) RunAndReturn(run func(req *http.Request) (bool, error)) *Authorizer_VerifyAdminRequest_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRequestSignature provides a mock function for the type Authorizer
func (_mock *Authorizer) VerifyRequestSignature(ctx context.Context, req *http.Request) (shared.AuthSession, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRequestSignature")
	}

	var r0 shared.AuthSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request) (shared.AuthSession, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request) shared.AuthSession); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.AuthSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *http.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Authorizer_VerifyRequestSignature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRequestSignature'
type Authorizer_VerifyRequestSignature_Call struct {
	*mock.Call
}

// VerifyRequestSignature is a helper method to define mock.On call
//   - ctx context.Context
//   - req *http.Request
func (_e *Authorizer_Expecter) VerifyRequestSignature(ctx interface{}, req interface{}) *Authorizer_VerifyRequestSignature_Call {
	return &Authorizer_VerifyRequestSignature_Call{Call: _e.mock.On("VerifyRequestSignature", ctx, req)}
}

func (_c *Authorizer_VerifyRequestSignature_Call) Run(run func(ctx context.Context, req *http.Request)) *Authorizer_VerifyRequestSignature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Authorizer_VerifyRequestSignature_Call) Return(authSession shared.AuthSession, err error) *Authorizer_VerifyRequestSignature_Call {
	_c.Call.Return(authSession, err)
	return _c
}

func (_c *Authorizer_VerifyRequestSignature_Call) RunAndReturn(run func(ctx context.Context, req *http.Request) (shared.AuthSession, error)) *Authorizer_VerifyRequestSignature_Call {
	_c.Call.Return(run)
	return _c
}
