// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/l3montree-dev/devguard/utils"
	mock "github.com/stretchr/testify/mock"
)

// NewModelWriter creates a new instance of ModelWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelWriter[ID any, T utils.Tabler, Tx any](t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelWriter[ID, T, Tx] {
	mock := &ModelWriter[ID, T, Tx]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ModelWriter is an autogenerated mock type for the ModelWriter type
type ModelWriter[ID any, T utils.Tabler, Tx any] struct {
	mock.Mock
}

type ModelWriter_Expecter[ID any, T utils.Tabler, Tx any] struct {
	mock *mock.Mock
}

func (_m *ModelWriter[ID, T, Tx]) EXPECT() *ModelWriter_Expecter[ID, T, Tx] {
	return &ModelWriter_Expecter[ID, T, Tx]{mock: &_m.Mock}
}

// Activate provides a mock function for the type ModelWriter
func (_mock *ModelWriter[ID, T, Tx]) Activate(ctx context.Context, tx Tx, id ID) error {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Tx, ID) error); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ModelWriter_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type ModelWriter_Activate_Call[ID any, T utils.Tabler, Tx any] struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - tx Tx
//   - id ID
func (_e *ModelWriter_Expecter[ID, T, Tx]) Activate(ctx interface{}, tx interface{}, id interface{}) *ModelWriter_Activate_Call[ID, T, Tx] {
	return &ModelWriter_Activate_Call[ID, T, Tx]{Call: _e.mock.On("Activate", ctx, tx, id)}
}

func (_c *ModelWriter_Activate_Call[ID, T, Tx]) Run(run func(ctx context.Context, tx Tx, id ID)) *ModelWriter_Activate_Call[ID, T, Tx] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Tx
		if args[1] != nil {
			arg1 = args[1].(Tx)
		}
		var arg2 ID
		if args[2] != nil {
			arg2 = args[2].(ID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ModelWriter_Activate_Call[ID, T, Tx]) Return(err error) *ModelWriter_Activate_Call[ID, T, Tx] {
	_c.Call.Return(err)
	return _c
}

func (_c *ModelWriter_Activate_Call[ID, T, Tx]) RunAndReturn(run func(ctx context.Context, tx Tx, id ID) error) *ModelWriter_Activate_Call[ID, T, Tx] {
	_c.Call.Return(run)
	return _c
}

// CleanupOrphanedRecords provides a mock function for the type ModelWriter
func (_mock *ModelWriter[ID, T, Tx]) CleanupOrphanedRecords(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOrphanedRecords")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ModelWriter_CleanupOrphanedRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupOrphanedRecords'
type ModelWriter_CleanupOrphanedRecords_Call[ID any, T utils.Tabler, Tx any] struct {
	*mock.Call
}

// CleanupOrphanedRecords is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ModelWriter_Expecter[ID, T, Tx]) CleanupOrphanedRecords(ctx interface{}) *ModelWriter_CleanupOrphanedRecords_Call[ID, T, Tx] {
	return &ModelWriter_CleanupOrphanedRecords_Call[ID, T, Tx]{Call: _e.mock.On("CleanupOrphanedRecords", ctx)}
}

func (_c *ModelWriter_CleanupOrphanedRecords_Call[ID, T, Tx]) Run(run func(ctx context.Context)) *ModelWriter_CleanupOrphanedRecords_Call[ID, T, Tx] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ModelWriter_CleanupOrphanedRecords_Call[ID, T, Tx]) Return(err error) *ModelWriter_CleanupOrphanedRecords_Call[ID, T, Tx] {
	_c.Call.Return(err)
	return _c
}

func (_c *ModelWriter_CleanupOrphanedRecords_Call[ID, T, Tx]) RunAndReturn(run func(ctx context.Context) error) *ModelWriter_CleanupOrphanedRecords_Call[ID, T, Tx] {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ModelWriter
func (_mock *ModelWriter[ID, T, Tx]) Create(ctx context.Context, tx Tx, t *T) error {
	ret := _mock.Called(ctx, tx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Tx, *T) error); ok {
		r0 = returnFunc(ctx, tx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ModelWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ModelWriter_Create_Call[ID any, T utils.Tabler, Tx any] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx Tx
//   - t *T
func (_e *ModelWriter_Expecter[ID, T, Tx]) Create(ctx interface{}, tx interface{}, t interface{}) *ModelWriter_Create_Call[ID, T, Tx] {
	return &ModelWriter_Create_Call[ID, T, Tx]{Call: _e.mock.On("Create", ctx, tx, t)}
}

func (_c *ModelWriter_Create_Call[ID, T, Tx]) Run(run func(ctx context.Context, tx Tx, t *T)) *ModelWriter_Create_Call[ID, T, Tx] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Tx
		if args[1] != nil {
			arg1 = args[1].(Tx)
		}
		var arg2 *T
		if args[2] != nil {
			arg2 = args[2].(*T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ModelWriter_Create_Call[ID, T, Tx]) Return(err error) *ModelWriter_Create_Call[ID, T, Tx] {
	_c.Call.Return(err)
	return _c
}

func (_c *ModelWriter_Create_Call[ID, T, Tx]) RunAndReturn(run func(ctx context.Context, tx Tx, t *T) error) *ModelWriter_Create_Call[ID, T, Tx] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ModelWriter
func (_mock *ModelWriter[ID, T, Tx]) Delete(ctx context.Context, tx Tx, id ID) error {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Tx, ID) error); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ModelWriter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ModelWriter_Delete_Call[ID any, T utils.Tabler, Tx any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tx Tx
//   - id ID
func (_e *ModelWriter_Expecter[ID, T, Tx]) Delete(ctx interface{}, tx interface{}, id interface{}) *ModelWriter_Delete_Call[ID, T, Tx] {
	return &ModelWriter_Delete_Call[ID, T, Tx]{Call: _e.mock.On("Delete", ctx, tx, id)}
}

func (_c *ModelWriter_Delete_Call[ID, T, Tx]) Run(run func(ctx context.Context, tx Tx, id ID)) *ModelWriter_Delete_Call[ID, T, Tx] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Tx
		if args[1] != nil {
			arg1 = args[1].(Tx)
		}
		var arg2 ID
		if args[2] != nil {
			arg2 = args[2].(ID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ModelWriter_Delete_Call[ID, T, Tx]) Return(err error) *ModelWriter_Delete_Call[ID, T, Tx] {
	_c.Call.Return(err)
	return _c
}

func (_c *ModelWriter_Delete_Call[ID, T, Tx]) RunAndReturn(run func(ctx context.Context, tx Tx, id ID) error) *ModelWriter_Delete_Call[ID, T, Tx] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type ModelWriter
func (_mock *ModelWriter[ID, T, Tx]) Save(ctx context.Context, tx Tx, t *T) error {
	ret := _mock.Called(ctx, tx, t)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Tx, *T) error); ok {
		r0 = returnFunc(ctx, tx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ModelWriter_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type ModelWriter_Save_Call[ID any, T utils.Tabler, Tx any] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - tx Tx
//   - t *T
func (_e *ModelWriter_Expecter[ID, T, Tx]) Save(ctx interface{}, tx interface{}, t interface{}) *ModelWriter_Save_Call[ID, T, Tx] {
	return &ModelWriter_Save_Call[ID, T, Tx]{Call: _e.mock.On("Save", ctx, tx, t)}
}

func (_c *ModelWriter_Save_Call[ID, T, Tx]) Run(run func(ctx context.Context, tx Tx, t *T)) *ModelWriter_Save_Call[ID, T, Tx] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Tx
		if args[1] != nil {
			arg1 = args[1].(Tx)
		}
		var arg2 *T
		if args[2] != nil {
			arg2 = args[2].(*T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ModelWriter_Save_Call[ID, T, Tx]) Return(err error) *ModelWriter_Save_Call[ID, T, Tx] {
	_c.Call.Return(err)
	return _c
}

func (_c *ModelWriter_Save_Call[ID, T, Tx]) RunAndReturn(run func(ctx context.Context, tx Tx, t *T) error) *ModelWriter_Save_Call[ID, T, Tx] {
	_c.Call.Return(run)
	return _c
}
