// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	models "github.com/l3montree-dev/flawfix/internal/database/models"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// FlawAssetRepository is an autogenerated mock type for the assetRepository type
type FlawAssetRepository struct {
	mock.Mock
}

type FlawAssetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FlawAssetRepository) EXPECT() *FlawAssetRepository_Expecter {
	return &FlawAssetRepository_Expecter{mock: &_m.Mock}
}

// Update provides a mock function with given fields: tx, asset
func (_m *FlawAssetRepository) Update(tx *gorm.DB, asset *models.Asset) error {
	ret := _m.Called(tx, asset)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.Asset) error); ok {
		r0 = rf(tx, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FlawAssetRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type FlawAssetRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - tx *gorm.DB
//   - asset *models.Asset
func (_e *FlawAssetRepository_Expecter) Update(tx interface{}, asset interface{}) *FlawAssetRepository_Update_Call {
	return &FlawAssetRepository_Update_Call{Call: _e.mock.On("Update", tx, asset)}
}

func (_c *FlawAssetRepository_Update_Call) Run(run func(tx *gorm.DB, asset *models.Asset)) *FlawAssetRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*models.Asset))
	})
	return _c
}

func (_c *FlawAssetRepository_Update_Call) Return(_a0 error) *FlawAssetRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FlawAssetRepository_Update_Call) RunAndReturn(run func(*gorm.DB, *models.Asset) error) *FlawAssetRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewFlawAssetRepository creates a new instance of FlawAssetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlawAssetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlawAssetRepository {
	mock := &FlawAssetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
