// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/l3montree-dev/devguard/database/models"
	"github.com/l3montree-dev/devguard/shared"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm/clause"
)

// NewReleaseRepository creates a new instance of ReleaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReleaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReleaseRepository {
	mock := &ReleaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ReleaseRepository is an autogenerated mock type for the ReleaseRepository type
type ReleaseRepository struct {
	mock.Mock
}

type ReleaseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReleaseRepository) EXPECT() *ReleaseRepository_Expecter {
	return &ReleaseRepository_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) Activate(ctx context.Context, tx shared.DB, id uuid.UUID) error {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type ReleaseRepository_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - id uuid.UUID
func (_e *ReleaseRepository_Expecter) Activate(ctx interface{}, tx interface{}, id interface{}) *ReleaseRepository_Activate_Call {
	return &ReleaseRepository_Activate_Call{Call: _e.mock.On("Activate", ctx, tx, id)}
}

func (_c *ReleaseRepository_Activate_Call) Run(run func(ctx context.Context, tx shared.DB, id uuid.UUID)) *ReleaseRepository_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_Activate_Call) Return(err error) *ReleaseRepository_Activate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_Activate_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, id uuid.UUID) error) *ReleaseRepository_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// All provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) All(ctx context.Context, tx shared.DB) ([]models.Release, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []models.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB) ([]models.Release, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB) []models.Release); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Release)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB) error); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReleaseRepository_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type ReleaseRepository_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
func (_e *ReleaseRepository_Expecter) All(ctx interface{}, tx interface{}) *ReleaseRepository_All_Call {
	return &ReleaseRepository_All_Call{Call: _e.mock.On("All", ctx, tx)}
}

func (_c *ReleaseRepository_All_Call) Run(run func(ctx context.Context, tx shared.DB)) *ReleaseRepository_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReleaseRepository_All_Call) Return(releases []models.Release, err error) *ReleaseRepository_All_Call {
	_c.Call.Return(releases, err)
	return _c
}

func (_c *ReleaseRepository_All_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB) ([]models.Release, error)) *ReleaseRepository_All_Call {
	_c.Call.Return(run)
	return _c
}

// Begin provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) Begin(ctx context.Context) shared.DB {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 shared.DB
	if returnFunc, ok := ret.Get(0).(func(context.Context) shared.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.DB)
		}
	}
	return r0
}

// ReleaseRepository_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type ReleaseRepository_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReleaseRepository_Expecter) Begin(ctx interface{}) *ReleaseRepository_Begin_Call {
	return &ReleaseRepository_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *ReleaseRepository_Begin_Call) Run(run func(ctx context.Context)) *ReleaseRepository_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ReleaseRepository_Begin_Call) Return(v shared.DB) *ReleaseRepository_Begin_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *ReleaseRepository_Begin_Call) RunAndReturn(run func(ctx context.Context) shared.DB) *ReleaseRepository_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// CleanupOrphanedRecords provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) CleanupOrphanedRecords(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOrphanedRecords")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_CleanupOrphanedRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupOrphanedRecords'
type ReleaseRepository_CleanupOrphanedRecords_Call struct {
	*mock.Call
}

// CleanupOrphanedRecords is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReleaseRepository_Expecter) CleanupOrphanedRecords(ctx interface{}) *ReleaseRepository_CleanupOrphanedRecords_Call {
	return &ReleaseRepository_CleanupOrphanedRecords_Call{Call: _e.mock.On("CleanupOrphanedRecords", ctx)}
}

func (_c *ReleaseRepository_CleanupOrphanedRecords_Call) Run(run func(ctx context.Context)) *ReleaseRepository_CleanupOrphanedRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ReleaseRepository_CleanupOrphanedRecords_Call) Return(err error) *ReleaseRepository_CleanupOrphanedRecords_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_CleanupOrphanedRecords_Call) RunAndReturn(run func(ctx context.Context) error) *ReleaseRepository_CleanupOrphanedRecords_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) Create(ctx context.Context, tx shared.DB, t *models.Release) error {
	ret := _mock.Called(ctx, tx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, *models.Release) error); ok {
		r0 = returnFunc(ctx, tx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReleaseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - t *models.Release
func (_e *ReleaseRepository_Expecter) Create(ctx interface{}, tx interface{}, t interface{}) *ReleaseRepository_Create_Call {
	return &ReleaseRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, t)}
}

func (_c *ReleaseRepository_Create_Call) Run(run func(ctx context.Context, tx shared.DB, t *models.Release)) *ReleaseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 *models.Release
		if args[2] != nil {
			arg2 = args[2].(*models.Release)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_Create_Call) Return(err error) *ReleaseRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, t *models.Release) error) *ReleaseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) CreateBatch(ctx context.Context, tx shared.DB, ts []models.Release) error {
	ret := _mock.Called(ctx, tx, ts)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []models.Release) error); ok {
		r0 = returnFunc(ctx, tx, ts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type ReleaseRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - ts []models.Release
func (_e *ReleaseRepository_Expecter) CreateBatch(ctx interface{}, tx interface{}, ts interface{}) *ReleaseRepository_CreateBatch_Call {
	return &ReleaseRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, tx, ts)}
}

func (_c *ReleaseRepository_CreateBatch_Call) Run(run func(ctx context.Context, tx shared.DB, ts []models.Release)) *ReleaseRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 []models.Release
		if args[2] != nil {
			arg2 = args[2].([]models.Release)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_CreateBatch_Call) Return(err error) *ReleaseRepository_CreateBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_CreateBatch_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, ts []models.Release) error) *ReleaseRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateReleaseItem provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) CreateReleaseItem(ctx context.Context, tx shared.DB, item *models.ReleaseItem) error {
	ret := _mock.Called(ctx, tx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateReleaseItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, *models.ReleaseItem) error); ok {
		r0 = returnFunc(ctx, tx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_CreateReleaseItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReleaseItem'
type ReleaseRepository_CreateReleaseItem_Call struct {
	*mock.Call
}

// CreateReleaseItem is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - item *models.ReleaseItem
func (_e *ReleaseRepository_Expecter) CreateReleaseItem(ctx interface{}, tx interface{}, item interface{}) *ReleaseRepository_CreateReleaseItem_Call {
	return &ReleaseRepository_CreateReleaseItem_Call{Call: _e.mock.On("CreateReleaseItem", ctx, tx, item)}
}

func (_c *ReleaseRepository_CreateReleaseItem_Call) Run(run func(ctx context.Context, tx shared.DB, item *models.ReleaseItem)) *ReleaseRepository_CreateReleaseItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 *models.ReleaseItem
		if args[2] != nil {
			arg2 = args[2].(*models.ReleaseItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_CreateReleaseItem_Call) Return(err error) *ReleaseRepository_CreateReleaseItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_CreateReleaseItem_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, item *models.ReleaseItem) error) *ReleaseRepository_CreateReleaseItem_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) Delete(ctx context.Context, tx shared.DB, id uuid.UUID) error {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ReleaseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - id uuid.UUID
func (_e *ReleaseRepository_Expecter) Delete(ctx interface{}, tx interface{}, id interface{}) *ReleaseRepository_Delete_Call {
	return &ReleaseRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, tx, id)}
}

func (_c *ReleaseRepository_Delete_Call) Run(run func(ctx context.Context, tx shared.DB, id uuid.UUID)) *ReleaseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_Delete_Call) Return(err error) *ReleaseRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, id uuid.UUID) error) *ReleaseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBatch provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) DeleteBatch(ctx context.Context, tx shared.DB, ids []models.Release) error {
	ret := _mock.Called(ctx, tx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []models.Release) error); ok {
		r0 = returnFunc(ctx, tx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_DeleteBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBatch'
type ReleaseRepository_DeleteBatch_Call struct {
	*mock.Call
}

// DeleteBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - ids []models.Release
func (_e *ReleaseRepository_Expecter) DeleteBatch(ctx interface{}, tx interface{}, ids interface{}) *ReleaseRepository_DeleteBatch_Call {
	return &ReleaseRepository_DeleteBatch_Call{Call: _e.mock.On("DeleteBatch", ctx, tx, ids)}
}

func (_c *ReleaseRepository_DeleteBatch_Call) Run(run func(ctx context.Context, tx shared.DB, ids []models.Release)) *ReleaseRepository_DeleteBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 []models.Release
		if args[2] != nil {
			arg2 = args[2].([]models.Release)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_DeleteBatch_Call) Return(err error) *ReleaseRepository_DeleteBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_DeleteBatch_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, ids []models.Release) error) *ReleaseRepository_DeleteBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReleaseItem provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) DeleteReleaseItem(ctx context.Context, tx shared.DB, id uuid.UUID) error {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReleaseItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_DeleteReleaseItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReleaseItem'
type ReleaseRepository_DeleteReleaseItem_Call struct {
	*mock.Call
}

// DeleteReleaseItem is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - id uuid.UUID
func (_e *ReleaseRepository_Expecter) DeleteReleaseItem(ctx interface{}, tx interface{}, id interface{}) *ReleaseRepository_DeleteReleaseItem_Call {
	return &ReleaseRepository_DeleteReleaseItem_Call{Call: _e.mock.On("DeleteReleaseItem", ctx, tx, id)}
}

func (_c *ReleaseRepository_DeleteReleaseItem_Call) Run(run func(ctx context.Context, tx shared.DB, id uuid.UUID)) *ReleaseRepository_DeleteReleaseItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_DeleteReleaseItem_Call) Return(err error) *ReleaseRepository_DeleteReleaseItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_DeleteReleaseItem_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, id uuid.UUID) error) *ReleaseRepository_DeleteReleaseItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProjectID provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) GetByProjectID(ctx context.Context, tx shared.DB, projectID uuid.UUID) ([]models.Release, error) {
	ret := _mock.Called(ctx, tx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProjectID")
	}

	var r0 []models.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) ([]models.Release, error)); ok {
		return returnFunc(ctx, tx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) []models.Release); ok {
		r0 = returnFunc(ctx, tx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Release)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReleaseRepository_GetByProjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProjectID'
type ReleaseRepository_GetByProjectID_Call struct {
	*mock.Call
}

// GetByProjectID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - projectID uuid.UUID
func (_e *ReleaseRepository_Expecter) GetByProjectID(ctx interface{}, tx interface{}, projectID interface{}) *ReleaseRepository_GetByProjectID_Call {
	return &ReleaseRepository_GetByProjectID_Call{Call: _e.mock.On("GetByProjectID", ctx, tx, projectID)}
}

func (_c *ReleaseRepository_GetByProjectID_Call) Run(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID)) *ReleaseRepository_GetByProjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_GetByProjectID_Call) Return(releases []models.Release, err error) *ReleaseRepository_GetByProjectID_Call {
	_c.Call.Return(releases, err)
	return _c
}

func (_c *ReleaseRepository_GetByProjectID_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID) ([]models.Release, error)) *ReleaseRepository_GetByProjectID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProjectIDPaged provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) GetByProjectIDPaged(ctx context.Context, tx shared.DB, projectID uuid.UUID, pageInfo shared.PageInfo, search string, filter []shared.FilterQuery, sort []shared.SortQuery) (shared.Paged[models.Release], error) {
	ret := _mock.Called(ctx, tx, projectID, pageInfo, search, filter, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetByProjectIDPaged")
	}

	var r0 shared.Paged[models.Release]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID, shared.PageInfo, string, []shared.FilterQuery, []shared.SortQuery) (shared.Paged[models.Release], error)); ok {
		return returnFunc(ctx, tx, projectID, pageInfo, search, filter, sort)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID, shared.PageInfo, string, []shared.FilterQuery, []shared.SortQuery) shared.Paged[models.Release]); ok {
		r0 = returnFunc(ctx, tx, projectID, pageInfo, search, filter, sort)
	} else {
		r0 = ret.Get(0).(shared.Paged[models.Release])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID, shared.PageInfo, string, []shared.FilterQuery, []shared.SortQuery) error); ok {
		r1 = returnFunc(ctx, tx, projectID, pageInfo, search, filter, sort)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReleaseRepository_GetByProjectIDPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProjectIDPaged'
type ReleaseRepository_GetByProjectIDPaged_Call struct {
	*mock.Call
}

// GetByProjectIDPaged is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - projectID uuid.UUID
//   - pageInfo shared.PageInfo
//   - search string
//   - filter []shared.FilterQuery
//   - sort []shared.SortQuery
func (_e *ReleaseRepository_Expecter) GetByProjectIDPaged(ctx interface{}, tx interface{}, projectID interface{}, pageInfo interface{}, search interface{}, filter interface{}, sort interface{}) *ReleaseRepository_GetByProjectIDPaged_Call {
	return &ReleaseRepository_GetByProjectIDPaged_Call{Call: _e.mock.On("GetByProjectIDPaged", ctx, tx, projectID, pageInfo, search, filter, sort)}
}

func (_c *ReleaseRepository_GetByProjectIDPaged_Call) Run(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID, pageInfo shared.PageInfo, search string, filter []shared.FilterQuery, sort []shared.SortQuery)) *ReleaseRepository_GetByProjectIDPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 shared.PageInfo
		if args[3] != nil {
			arg3 = args[3].(shared.PageInfo)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []shared.FilterQuery
		if args[5] != nil {
			arg5 = args[5].([]shared.FilterQuery)
		}
		var arg6 []shared.SortQuery
		if args[6] != nil {
			arg6 = args[6].([]shared.SortQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *ReleaseRepository_GetByProjectIDPaged_Call) Return(paged shared.Paged[models.Release], err error) *ReleaseRepository_GetByProjectIDPaged_Call {
	_c.Call.Return(paged, err)
	return _c
}

func (_c *ReleaseRepository_GetByProjectIDPaged_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID, pageInfo shared.PageInfo, search string, filter []shared.FilterQuery, sort []shared.SortQuery) (shared.Paged[models.Release], error)) *ReleaseRepository_GetByProjectIDPaged_Call {
	_c.Call.Return(run)
	return _c
}

// GetCandidateItemsForRelease provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) GetCandidateItemsForRelease(ctx context.Context, tx shared.DB, projectID uuid.UUID, releaseID *uuid.UUID) ([]models.Artifact, []models.Release, error) {
	ret := _mock.Called(ctx, tx, projectID, releaseID)

	if len(ret) == 0 {
		panic("no return value specified for GetCandidateItemsForRelease")
	}

	var r0 []models.Artifact
	var r1 []models.Release
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID, *uuid.UUID) ([]models.Artifact, []models.Release, error)); ok {
		return returnFunc(ctx, tx, projectID, releaseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID, *uuid.UUID) []models.Artifact); ok {
		r0 = returnFunc(ctx, tx, projectID, releaseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID, *uuid.UUID) []models.Release); ok {
		r1 = returnFunc(ctx, tx, projectID, releaseID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]models.Release)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, shared.DB, uuid.UUID, *uuid.UUID) error); ok {
		r2 = returnFunc(ctx, tx, projectID, releaseID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ReleaseRepository_GetCandidateItemsForRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCandidateItemsForRelease'
type ReleaseRepository_GetCandidateItemsForRelease_Call struct {
	*mock.Call
}

// GetCandidateItemsForRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - projectID uuid.UUID
//   - releaseID *uuid.UUID
func (_e *ReleaseRepository_Expecter) GetCandidateItemsForRelease(ctx interface{}, tx interface{}, projectID interface{}, releaseID interface{}) *ReleaseRepository_GetCandidateItemsForRelease_Call {
	return &ReleaseRepository_GetCandidateItemsForRelease_Call{Call: _e.mock.On("GetCandidateItemsForRelease", ctx, tx, projectID, releaseID)}
}

func (_c *ReleaseRepository_GetCandidateItemsForRelease_Call) Run(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID, releaseID *uuid.UUID)) *ReleaseRepository_GetCandidateItemsForRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ReleaseRepository_GetCandidateItemsForRelease_Call) Return(artifacts []models.Artifact, releases []models.Release, err error) *ReleaseRepository_GetCandidateItemsForRelease_Call {
	_c.Call.Return(artifacts, releases, err)
	return _c
}

func (_c *ReleaseRepository_GetCandidateItemsForRelease_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID, releaseID *uuid.UUID) ([]models.Artifact, []models.Release, error)) *ReleaseRepository_GetCandidateItemsForRelease_Call {
	_c.Call.Return(run)
	return _c
}

// GetDB provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) GetDB(ctx context.Context, tx shared.DB) shared.DB {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 shared.DB
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB) shared.DB); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.DB)
		}
	}
	return r0
}

// ReleaseRepository_GetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDB'
type ReleaseRepository_GetDB_Call struct {
	*mock.Call
}

// GetDB is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
func (_e *ReleaseRepository_Expecter) GetDB(ctx interface{}, tx interface{}) *ReleaseRepository_GetDB_Call {
	return &ReleaseRepository_GetDB_Call{Call: _e.mock.On("GetDB", ctx, tx)}
}

func (_c *ReleaseRepository_GetDB_Call) Run(run func(ctx context.Context, tx shared.DB)) *ReleaseRepository_GetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReleaseRepository_GetDB_Call) Return(v shared.DB) *ReleaseRepository_GetDB_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *ReleaseRepository_GetDB_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB) shared.DB) *ReleaseRepository_GetDB_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) List(ctx context.Context, tx shared.DB, ids []uuid.UUID) ([]models.Release, error) {
	ret := _mock.Called(ctx, tx, ids)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []uuid.UUID) ([]models.Release, error)); ok {
		return returnFunc(ctx, tx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []uuid.UUID) []models.Release); ok {
		r0 = returnFunc(ctx, tx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Release)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReleaseRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ReleaseRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - ids []uuid.UUID
func (_e *ReleaseRepository_Expecter) List(ctx interface{}, tx interface{}, ids interface{}) *ReleaseRepository_List_Call {
	return &ReleaseRepository_List_Call{Call: _e.mock.On("List", ctx, tx, ids)}
}

func (_c *ReleaseRepository_List_Call) Run(run func(ctx context.Context, tx shared.DB, ids []uuid.UUID)) *ReleaseRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_List_Call) Return(releases []models.Release, err error) *ReleaseRepository_List_Call {
	_c.Call.Return(releases, err)
	return _c
}

func (_c *ReleaseRepository_List_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, ids []uuid.UUID) ([]models.Release, error)) *ReleaseRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) Read(ctx context.Context, tx shared.DB, id uuid.UUID) (models.Release, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 models.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) (models.Release, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) models.Release); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(models.Release)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReleaseRepository_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type ReleaseRepository_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - id uuid.UUID
func (_e *ReleaseRepository_Expecter) Read(ctx interface{}, tx interface{}, id interface{}) *ReleaseRepository_Read_Call {
	return &ReleaseRepository_Read_Call{Call: _e.mock.On("Read", ctx, tx, id)}
}

func (_c *ReleaseRepository_Read_Call) Run(run func(ctx context.Context, tx shared.DB, id uuid.UUID)) *ReleaseRepository_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_Read_Call) Return(release models.Release, err error) *ReleaseRepository_Read_Call {
	_c.Call.Return(release, err)
	return _c
}

func (_c *ReleaseRepository_Read_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, id uuid.UUID) (models.Release, error)) *ReleaseRepository_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadRecursive provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) ReadRecursive(ctx context.Context, tx shared.DB, id uuid.UUID) (models.Release, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for ReadRecursive")
	}

	var r0 models.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) (models.Release, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) models.Release); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(models.Release)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReleaseRepository_ReadRecursive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRecursive'
type ReleaseRepository_ReadRecursive_Call struct {
	*mock.Call
}

// ReadRecursive is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - id uuid.UUID
func (_e *ReleaseRepository_Expecter) ReadRecursive(ctx interface{}, tx interface{}, id interface{}) *ReleaseRepository_ReadRecursive_Call {
	return &ReleaseRepository_ReadRecursive_Call{Call: _e.mock.On("ReadRecursive", ctx, tx, id)}
}

func (_c *ReleaseRepository_ReadRecursive_Call) Run(run func(ctx context.Context, tx shared.DB, id uuid.UUID)) *ReleaseRepository_ReadRecursive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_ReadRecursive_Call) Return(release models.Release, err error) *ReleaseRepository_ReadRecursive_Call {
	_c.Call.Return(release, err)
	return _c
}

func (_c *ReleaseRepository_ReadRecursive_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, id uuid.UUID) (models.Release, error)) *ReleaseRepository_ReadRecursive_Call {
	_c.Call.Return(run)
	return _c
}

// ReadWithItems provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) ReadWithItems(ctx context.Context, tx shared.DB, id uuid.UUID) (models.Release, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for ReadWithItems")
	}

	var r0 models.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) (models.Release, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) models.Release); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(models.Release)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReleaseRepository_ReadWithItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadWithItems'
type ReleaseRepository_ReadWithItems_Call struct {
	*mock.Call
}

// ReadWithItems is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - id uuid.UUID
func (_e *ReleaseRepository_Expecter) ReadWithItems(ctx interface{}, tx interface{}, id interface{}) *ReleaseRepository_ReadWithItems_Call {
	return &ReleaseRepository_ReadWithItems_Call{Call: _e.mock.On("ReadWithItems", ctx, tx, id)}
}

func (_c *ReleaseRepository_ReadWithItems_Call) Run(run func(ctx context.Context, tx shared.DB, id uuid.UUID)) *ReleaseRepository_ReadWithItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_ReadWithItems_Call) Return(release models.Release, err error) *ReleaseRepository_ReadWithItems_Call {
	_c.Call.Return(release, err)
	return _c
}

func (_c *ReleaseRepository_ReadWithItems_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, id uuid.UUID) (models.Release, error)) *ReleaseRepository_ReadWithItems_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) Save(ctx context.Context, tx shared.DB, t *models.Release) error {
	ret := _mock.Called(ctx, tx, t)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, *models.Release) error); ok {
		r0 = returnFunc(ctx, tx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type ReleaseRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - t *models.Release
func (_e *ReleaseRepository_Expecter) Save(ctx interface{}, tx interface{}, t interface{}) *ReleaseRepository_Save_Call {
	return &ReleaseRepository_Save_Call{Call: _e.mock.On("Save", ctx, tx, t)}
}

func (_c *ReleaseRepository_Save_Call) Run(run func(ctx context.Context, tx shared.DB, t *models.Release)) *ReleaseRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 *models.Release
		if args[2] != nil {
			arg2 = args[2].(*models.Release)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_Save_Call) Return(err error) *ReleaseRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_Save_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, t *models.Release) error) *ReleaseRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) SaveBatch(ctx context.Context, tx shared.DB, ts []models.Release) error {
	ret := _mock.Called(ctx, tx, ts)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []models.Release) error); ok {
		r0 = returnFunc(ctx, tx, ts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type ReleaseRepository_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - ts []models.Release
func (_e *ReleaseRepository_Expecter) SaveBatch(ctx interface{}, tx interface{}, ts interface{}) *ReleaseRepository_SaveBatch_Call {
	return &ReleaseRepository_SaveBatch_Call{Call: _e.mock.On("SaveBatch", ctx, tx, ts)}
}

func (_c *ReleaseRepository_SaveBatch_Call) Run(run func(ctx context.Context, tx shared.DB, ts []models.Release)) *ReleaseRepository_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 []models.Release
		if args[2] != nil {
			arg2 = args[2].([]models.Release)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_SaveBatch_Call) Return(err error) *ReleaseRepository_SaveBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_SaveBatch_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, ts []models.Release) error) *ReleaseRepository_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatchBestEffort provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) SaveBatchBestEffort(ctx context.Context, tx shared.DB, ts []models.Release) error {
	ret := _mock.Called(ctx, tx, ts)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatchBestEffort")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []models.Release) error); ok {
		r0 = returnFunc(ctx, tx, ts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_SaveBatchBestEffort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatchBestEffort'
type ReleaseRepository_SaveBatchBestEffort_Call struct {
	*mock.Call
}

// SaveBatchBestEffort is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - ts []models.Release
func (_e *ReleaseRepository_Expecter) SaveBatchBestEffort(ctx interface{}, tx interface{}, ts interface{}) *ReleaseRepository_SaveBatchBestEffort_Call {
	return &ReleaseRepository_SaveBatchBestEffort_Call{Call: _e.mock.On("SaveBatchBestEffort", ctx, tx, ts)}
}

func (_c *ReleaseRepository_SaveBatchBestEffort_Call) Run(run func(ctx context.Context, tx shared.DB, ts []models.Release)) *ReleaseRepository_SaveBatchBestEffort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 []models.Release
		if args[2] != nil {
			arg2 = args[2].([]models.Release)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReleaseRepository_SaveBatchBestEffort_Call) Return(err error) *ReleaseRepository_SaveBatchBestEffort_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_SaveBatchBestEffort_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, ts []models.Release) error) *ReleaseRepository_SaveBatchBestEffort_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) Transaction(ctx context.Context, fn func(tx shared.DB) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx shared.DB) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type ReleaseRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx shared.DB) error
func (_e *ReleaseRepository_Expecter) Transaction(ctx interface{}, fn interface{}) *ReleaseRepository_Transaction_Call {
	return &ReleaseRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *ReleaseRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(tx shared.DB) error)) *ReleaseRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx shared.DB) error
		if args[1] != nil {
			arg1 = args[1].(func(tx shared.DB) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReleaseRepository_Transaction_Call) Return(err error) *ReleaseRepository_Transaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_Transaction_Call) RunAndReturn(run func(ctx context.Context, fn func(tx shared.DB) error) error) *ReleaseRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type ReleaseRepository
func (_mock *ReleaseRepository) Upsert(ctx context.Context, tx shared.DB, t *[]*models.Release, conflictingColumns []clause.Column, updateOnly []string) error {
	ret := _mock.Called(ctx, tx, t, conflictingColumns, updateOnly)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, *[]*models.Release, []clause.Column, []string) error); ok {
		r0 = returnFunc(ctx, tx, t, conflictingColumns, updateOnly)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReleaseRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type ReleaseRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - t *[]*models.Release
//   - conflictingColumns []clause.Column
//   - updateOnly []string
func (_e *ReleaseRepository_Expecter) Upsert(ctx interface{}, tx interface{}, t interface{}, conflictingColumns interface{}, updateOnly interface{}) *ReleaseRepository_Upsert_Call {
	return &ReleaseRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, tx, t, conflictingColumns, updateOnly)}
}

func (_c *ReleaseRepository_Upsert_Call) Run(run func(ctx context.Context, tx shared.DB, t *[]*models.Release, conflictingColumns []clause.Column, updateOnly []string)) *ReleaseRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 *[]*models.Release
		if args[2] != nil {
			arg2 = args[2].(*[]*models.Release)
		}
		var arg3 []clause.Column
		if args[3] != nil {
			arg3 = args[3].([]clause.Column)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ReleaseRepository_Upsert_Call) Return(err error) *ReleaseRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReleaseRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, t *[]*models.Release, conflictingColumns []clause.Column, updateOnly []string) error) *ReleaseRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
