// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	"github.com/l3montree-dev/devguard/shared"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthorizer creates a new instance of Authorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authorizer {
	mock := &Authorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Authorizer is an autogenerated mock type for the Authorizer type
type Authorizer struct {
	mock.Mock
}

type Authorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *Authorizer) EXPECT() *Authorizer_Expecter {
	return &Authorizer_Expecter{mock: &_m.Mock}
}

// VerifyAPIToken provides a mock function for the type Authorizer
func (_mock *Authorizer) VerifyAPIToken(ctx context.Context, token string) (shared.AuthSession, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAPIToken")
	}

	var r0 shared.AuthSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (shared.AuthSession, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) shared.AuthSession); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.AuthSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Authorizer_VerifyAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAPIToken'
type Authorizer_VerifyAPIToken_Call struct {
	*mock.Call
}

// VerifyAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Authorizer_Expecter) VerifyAPIToken(ctx interface{}, token interface{}) *Authorizer_VerifyAPIToken_Call {
	return &Authorizer_VerifyAPIToken_Call{Call: _e.mock.On("VerifyAPIToken", ctx, token)}
}

func (_c *Authorizer_VerifyAPIToken_Call) Run(run func(ctx context.Context, token string)) *Authorizer_VerifyAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Authorizer_VerifyAPIToken_Call) Return(authSession shared.AuthSession, err error) *Authorizer_VerifyAPIToken_Call {
	_c.Call.Return(authSession, err)
	return _c
}

func (_c *Authorizer_VerifyAPIToken_Call) RunAndReturn(run func(ctx context.Context, token string) (shared.AuthSession, error)) *Authorizer_VerifyAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAdminRequest provides a mock function for the type Authorizer
func (_mock *Authorizer) VerifyAdminRequest(req *http.Request) (bool, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAdminRequest")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (bool, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) bool); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Authorizer_VerifyAdminRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAdminRequest'
type Authorizer_VerifyAdminRequest_Call struct {
	*mock.Call
}

// VerifyAdminRequest is a helper method to define mock.On call
//   - req *http.Request
func (_e *Authorizer_Expecter) VerifyAdminRequest(req interface{}) *Authorizer_VerifyAdminRequest_Call {
	return &Authorizer_VerifyAdminRequest_Call{Call: _e.mock.On("VerifyAdminRequest", req)}
}

func (_c *Authorizer_VerifyAdminRequest_Call) Run(run func(req *http.Request)) *Authorizer_VerifyAdminRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Authorizer_VerifyAdminRequest_Call) Return(b bool, err error) *Authorizer_VerifyAdminRequest_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Authorizer_VerifyAdminRequest_Call) RunAndReturn(run func(req *http.Request) (bool, error)) *Authorizer_VerifyAdminRequest_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRequestSignature provides a mock function for the type Authorizer
func (_mock *Authorizer) VerifyRequestSignature(ctx context.Context, req *http.Request) (shared.AuthSession, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRequestSignature")
	}

	var r0 shared.AuthSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request) (shared.AuthSession, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request) shared.AuthSession); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.AuthSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *http.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Authorizer_VerifyRequestSignature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRequestSignature'
type Authorizer_VerifyRequestSignature_Call struct {
	*mock.Call
}

// VerifyRequestSignature is a helper method to define mock.On call
//   - ctx context.Context
//   - req *http.Request
func (_e *Authorizer_Expecter) VerifyRequestSignature(ctx interface{}, req interface{}) *Authorizer_VerifyRequestSignature_Call {
	return &Authorizer_VerifyRequestSignature_Call{Call: _e.mock.On("VerifyRequestSignature", ctx, req)}
}

func (_c *Authorizer_VerifyRequestSignature_Call) Run(run func(ctx context.Context, req *http.Request)) *Authorizer_VerifyRequestSignature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Authorizer_VerifyRequestSignature_Call) Return(authSession shared.AuthSession, err error) *Authorizer_VerifyRequestSignature_Call {
	_c.Call.Return(authSession, err)
	return _c
}

func (_c *Authorizer_VerifyRequestSignature_Call) RunAndReturn(run func(ctx context.Context, req *http.Request) (shared.AuthSession, error)) *Authorizer_VerifyRequestSignature_Call {
	_c.Call.Return(run)
	return _c
}
