// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VulndbLeaderElector is an autogenerated mock type for the leaderElector type
type VulndbLeaderElector struct {
	mock.Mock
}

type VulndbLeaderElector_Expecter struct {
	mock *mock.Mock
}

func (_m *VulndbLeaderElector) EXPECT() *VulndbLeaderElector_Expecter {
	return &VulndbLeaderElector_Expecter{mock: &_m.Mock}
}

// IfLeader provides a mock function with given fields: ctx, fn
func (_m *VulndbLeaderElector) IfLeader(ctx context.Context, fn func() error) {
	_m.Called(ctx, fn)
}

// VulndbLeaderElector_IfLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IfLeader'
type VulndbLeaderElector_IfLeader_Call struct {
	*mock.Call
}

// IfLeader is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func() error
func (_e *VulndbLeaderElector_Expecter) IfLeader(ctx interface{}, fn interface{}) *VulndbLeaderElector_IfLeader_Call {
	return &VulndbLeaderElector_IfLeader_Call{Call: _e.mock.On("IfLeader", ctx, fn)}
}

func (_c *VulndbLeaderElector_IfLeader_Call) Run(run func(ctx context.Context, fn func() error)) *VulndbLeaderElector_IfLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func() error))
	})
	return _c
}

func (_c *VulndbLeaderElector_IfLeader_Call) Return() *VulndbLeaderElector_IfLeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *VulndbLeaderElector_IfLeader_Call) RunAndReturn(run func(context.Context, func() error)) *VulndbLeaderElector_IfLeader_Call {
	_c.Call.Return(run)
	return _c
}

// NewVulndbLeaderElector creates a new instance of VulndbLeaderElector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVulndbLeaderElector(t interface {
	mock.TestingT
	Cleanup(func())
}) *VulndbLeaderElector {
	mock := &VulndbLeaderElector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
