// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/l3montree-dev/devguard/fixedversion"
	"github.com/package-url/packageurl-go"
	mock "github.com/stretchr/testify/mock"
)

// NewResolver creates a new instance of Resolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResolver[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Resolver[T] {
	mock := &Resolver[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Resolver is an autogenerated mock type for the Resolver type
type Resolver[T any] struct {
	mock.Mock
}

type Resolver_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *Resolver[T]) EXPECT() *Resolver_Expecter[T] {
	return &Resolver_Expecter[T]{mock: &_m.Mock}
}

// CheckIfVulnerabilityIsFixed provides a mock function for the type Resolver
func (_mock *Resolver[T]) CheckIfVulnerabilityIsFixed(vulnVersion string, fixedVersion string) bool {
	ret := _mock.Called(vulnVersion, fixedVersion)

	if len(ret) == 0 {
		panic("no return value specified for CheckIfVulnerabilityIsFixed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(vulnVersion, fixedVersion)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Resolver_CheckIfVulnerabilityIsFixed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIfVulnerabilityIsFixed'
type Resolver_CheckIfVulnerabilityIsFixed_Call[T any] struct {
	*mock.Call
}

// CheckIfVulnerabilityIsFixed is a helper method to define mock.On call
//   - vulnVersion string
//   - fixedVersion string
func (_e *Resolver_Expecter[T]) CheckIfVulnerabilityIsFixed(vulnVersion interface{}, fixedVersion interface{}) *Resolver_CheckIfVulnerabilityIsFixed_Call[T] {
	return &Resolver_CheckIfVulnerabilityIsFixed_Call[T]{Call: _e.mock.On("CheckIfVulnerabilityIsFixed", vulnVersion, fixedVersion)}
}

func (_c *Resolver_CheckIfVulnerabilityIsFixed_Call[T]) Run(run func(vulnVersion string, fixedVersion string)) *Resolver_CheckIfVulnerabilityIsFixed_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Resolver_CheckIfVulnerabilityIsFixed_Call[T]) Return(b bool) *Resolver_CheckIfVulnerabilityIsFixed_Call[T] {
	_c.Call.Return(b)
	return _c
}

func (_c *Resolver_CheckIfVulnerabilityIsFixed_Call[T]) RunAndReturn(run func(vulnVersion string, fixedVersion string) bool) *Resolver_CheckIfVulnerabilityIsFixed_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FetchPackageMetadata provides a mock function for the type Resolver
func (_mock *Resolver[T]) FetchPackageMetadata(purl packageurl.PackageURL) (T, error) {
	ret := _mock.Called(purl)

	if len(ret) == 0 {
		panic("no return value specified for FetchPackageMetadata")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(packageurl.PackageURL) (T, error)); ok {
		return returnFunc(purl)
	}
	if returnFunc, ok := ret.Get(0).(func(packageurl.PackageURL) T); ok {
		r0 = returnFunc(purl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(packageurl.PackageURL) error); ok {
		r1 = returnFunc(purl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Resolver_FetchPackageMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPackageMetadata'
type Resolver_FetchPackageMetadata_Call[T any] struct {
	*mock.Call
}

// FetchPackageMetadata is a helper method to define mock.On call
//   - purl packageurl.PackageURL
func (_e *Resolver_Expecter[T]) FetchPackageMetadata(purl interface{}) *Resolver_FetchPackageMetadata_Call[T] {
	return &Resolver_FetchPackageMetadata_Call[T]{Call: _e.mock.On("FetchPackageMetadata", purl)}
}

func (_c *Resolver_FetchPackageMetadata_Call[T]) Run(run func(purl packageurl.PackageURL)) *Resolver_FetchPackageMetadata_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 packageurl.PackageURL
		if args[0] != nil {
			arg0 = args[0].(packageurl.PackageURL)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Resolver_FetchPackageMetadata_Call[T]) Return(v T, err error) *Resolver_FetchPackageMetadata_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Resolver_FetchPackageMetadata_Call[T]) RunAndReturn(run func(purl packageurl.PackageURL) (T, error)) *Resolver_FetchPackageMetadata_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindDependencyVersionInMeta provides a mock function for the type Resolver
func (_mock *Resolver[T]) FindDependencyVersionInMeta(depMeta T, pkgName string) (fixedversion.VersionConstraint, bool) {
	ret := _mock.Called(depMeta, pkgName)

	if len(ret) == 0 {
		panic("no return value specified for FindDependencyVersionInMeta")
	}

	var r0 fixedversion.VersionConstraint
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(T, string) (fixedversion.VersionConstraint, bool)); ok {
		return returnFunc(depMeta, pkgName)
	}
	if returnFunc, ok := ret.Get(0).(func(T, string) fixedversion.VersionConstraint); ok {
		r0 = returnFunc(depMeta, pkgName)
	} else {
		r0 = ret.Get(0).(fixedversion.VersionConstraint)
	}
	if returnFunc, ok := ret.Get(1).(func(T, string) bool); ok {
		r1 = returnFunc(depMeta, pkgName)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// Resolver_FindDependencyVersionInMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDependencyVersionInMeta'
type Resolver_FindDependencyVersionInMeta_Call[T any] struct {
	*mock.Call
}

// FindDependencyVersionInMeta is a helper method to define mock.On call
//   - depMeta T
//   - pkgName string
func (_e *Resolver_Expecter[T]) FindDependencyVersionInMeta(depMeta interface{}, pkgName interface{}) *Resolver_FindDependencyVersionInMeta_Call[T] {
	return &Resolver_FindDependencyVersionInMeta_Call[T]{Call: _e.mock.On("FindDependencyVersionInMeta", depMeta, pkgName)}
}

func (_c *Resolver_FindDependencyVersionInMeta_Call[T]) Run(run func(depMeta T, pkgName string)) *Resolver_FindDependencyVersionInMeta_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Resolver_FindDependencyVersionInMeta_Call[T]) Return(versionConstraint fixedversion.VersionConstraint, b bool) *Resolver_FindDependencyVersionInMeta_Call[T] {
	_c.Call.Return(versionConstraint, b)
	return _c
}

func (_c *Resolver_FindDependencyVersionInMeta_Call[T]) RunAndReturn(run func(depMeta T, pkgName string) (fixedversion.VersionConstraint, bool)) *Resolver_FindDependencyVersionInMeta_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetUpgradeCandidates provides a mock function for the type Resolver
func (_mock *Resolver[T]) GetUpgradeCandidates(allVersionsMeta T, currentVersion string) ([]string, error) {
	ret := _mock.Called(allVersionsMeta, currentVersion)

	if len(ret) == 0 {
		panic("no return value specified for GetUpgradeCandidates")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(T, string) ([]string, error)); ok {
		return returnFunc(allVersionsMeta, currentVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(T, string) []string); ok {
		r0 = returnFunc(allVersionsMeta, currentVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(T, string) error); ok {
		r1 = returnFunc(allVersionsMeta, currentVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Resolver_GetUpgradeCandidates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpgradeCandidates'
type Resolver_GetUpgradeCandidates_Call[T any] struct {
	*mock.Call
}

// GetUpgradeCandidates is a helper method to define mock.On call
//   - allVersionsMeta T
//   - currentVersion string
func (_e *Resolver_Expecter[T]) GetUpgradeCandidates(allVersionsMeta interface{}, currentVersion interface{}) *Resolver_GetUpgradeCandidates_Call[T] {
	return &Resolver_GetUpgradeCandidates_Call[T]{Call: _e.mock.On("GetUpgradeCandidates", allVersionsMeta, currentVersion)}
}

func (_c *Resolver_GetUpgradeCandidates_Call[T]) Run(run func(allVersionsMeta T, currentVersion string)) *Resolver_GetUpgradeCandidates_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Resolver_GetUpgradeCandidates_Call[T]) Return(strings []string, err error) *Resolver_GetUpgradeCandidates_Call[T] {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Resolver_GetUpgradeCandidates_Call[T]) RunAndReturn(run func(allVersionsMeta T, currentVersion string) ([]string, error)) *Resolver_GetUpgradeCandidates_Call[T] {
	_c.Call.Return(run)
	return _c
}

// ParseVersionConstraint provides a mock function for the type Resolver
func (_mock *Resolver[T]) ParseVersionConstraint(spec string) (string, string) {
	ret := _mock.Called(spec)

	if len(ret) == 0 {
		panic("no return value specified for ParseVersionConstraint")
	}

	var r0 string
	var r1 string
	if returnFunc, ok := ret.Get(0).(func(string) (string, string)); ok {
		return returnFunc(spec)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(spec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) string); ok {
		r1 = returnFunc(spec)
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// Resolver_ParseVersionConstraint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseVersionConstraint'
type Resolver_ParseVersionConstraint_Call[T any] struct {
	*mock.Call
}

// ParseVersionConstraint is a helper method to define mock.On call
//   - spec string
func (_e *Resolver_Expecter[T]) ParseVersionConstraint(spec interface{}) *Resolver_ParseVersionConstraint_Call[T] {
	return &Resolver_ParseVersionConstraint_Call[T]{Call: _e.mock.On("ParseVersionConstraint", spec)}
}

func (_c *Resolver_ParseVersionConstraint_Call[T]) Run(run func(spec string)) *Resolver_ParseVersionConstraint_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Resolver_ParseVersionConstraint_Call[T]) Return(rangeType string, baseVersion string) *Resolver_ParseVersionConstraint_Call[T] {
	_c.Call.Return(rangeType, baseVersion)
	return _c
}

func (_c *Resolver_ParseVersionConstraint_Call[T]) RunAndReturn(run func(spec string) (string, string)) *Resolver_ParseVersionConstraint_Call[T] {
	_c.Call.Return(run)
	return _c
}

// ResolveBestVersion provides a mock function for the type Resolver
func (_mock *Resolver[T]) ResolveBestVersion(allVersionsMeta T, versionConstraint fixedversion.VersionConstraint, currentVersion string) (string, error) {
	ret := _mock.Called(allVersionsMeta, versionConstraint, currentVersion)

	if len(ret) == 0 {
		panic("no return value specified for ResolveBestVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(T, fixedversion.VersionConstraint, string) (string, error)); ok {
		return returnFunc(allVersionsMeta, versionConstraint, currentVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(T, fixedversion.VersionConstraint, string) string); ok {
		r0 = returnFunc(allVersionsMeta, versionConstraint, currentVersion)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(T, fixedversion.VersionConstraint, string) error); ok {
		r1 = returnFunc(allVersionsMeta, versionConstraint, currentVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Resolver_ResolveBestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveBestVersion'
type Resolver_ResolveBestVersion_Call[T any] struct {
	*mock.Call
}

// ResolveBestVersion is a helper method to define mock.On call
//   - allVersionsMeta T
//   - versionConstraint fixedversion.VersionConstraint
//   - currentVersion string
func (_e *Resolver_Expecter[T]) ResolveBestVersion(allVersionsMeta interface{}, versionConstraint interface{}, currentVersion interface{}) *Resolver_ResolveBestVersion_Call[T] {
	return &Resolver_ResolveBestVersion_Call[T]{Call: _e.mock.On("ResolveBestVersion", allVersionsMeta, versionConstraint, currentVersion)}
}

func (_c *Resolver_ResolveBestVersion_Call[T]) Run(run func(allVersionsMeta T, versionConstraint fixedversion.VersionConstraint, currentVersion string)) *Resolver_ResolveBestVersion_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		var arg1 fixedversion.VersionConstraint
		if args[1] != nil {
			arg1 = args[1].(fixedversion.VersionConstraint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Resolver_ResolveBestVersion_Call[T]) Return(s string, err error) *Resolver_ResolveBestVersion_Call[T] {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Resolver_ResolveBestVersion_Call[T]) RunAndReturn(run func(allVersionsMeta T, versionConstraint fixedversion.VersionConstraint, currentVersion string) (string, error)) *Resolver_ResolveBestVersion_Call[T] {
	_c.Call.Return(run)
	return _c
}
