// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/l3montree-dev/devguard/database/models"
	"github.com/l3montree-dev/devguard/shared"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm/clause"
)

// NewAssetRepository creates a new instance of AssetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssetRepository {
	mock := &AssetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AssetRepository is an autogenerated mock type for the AssetRepository type
type AssetRepository struct {
	mock.Mock
}

type AssetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AssetRepository) EXPECT() *AssetRepository_Expecter {
	return &AssetRepository_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function for the type AssetRepository
func (_mock *AssetRepository) Activate(ctx context.Context, tx shared.DB, id uuid.UUID) error {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssetRepository_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type AssetRepository_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - id uuid.UUID
func (_e *AssetRepository_Expecter) Activate(ctx interface{}, tx interface{}, id interface{}) *AssetRepository_Activate_Call {
	return &AssetRepository_Activate_Call{Call: _e.mock.On("Activate", ctx, tx, id)}
}

func (_c *AssetRepository_Activate_Call) Run(run func(ctx context.Context, tx shared.DB, id uuid.UUID)) *AssetRepository_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_Activate_Call) Return(err error) *AssetRepository_Activate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssetRepository_Activate_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, id uuid.UUID) error) *AssetRepository_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// All provides a mock function for the type AssetRepository
func (_mock *AssetRepository) All(ctx context.Context, tx shared.DB) ([]models.Asset, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB) ([]models.Asset, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB) []models.Asset); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Asset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB) error); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type AssetRepository_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
func (_e *AssetRepository_Expecter) All(ctx interface{}, tx interface{}) *AssetRepository_All_Call {
	return &AssetRepository_All_Call{Call: _e.mock.On("All", ctx, tx)}
}

func (_c *AssetRepository_All_Call) Run(run func(ctx context.Context, tx shared.DB)) *AssetRepository_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AssetRepository_All_Call) Return(assets []models.Asset, err error) *AssetRepository_All_Call {
	_c.Call.Return(assets, err)
	return _c
}

func (_c *AssetRepository_All_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB) ([]models.Asset, error)) *AssetRepository_All_Call {
	_c.Call.Return(run)
	return _c
}

// Begin provides a mock function for the type AssetRepository
func (_mock *AssetRepository) Begin(ctx context.Context) shared.DB {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 shared.DB
	if returnFunc, ok := ret.Get(0).(func(context.Context) shared.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.DB)
		}
	}
	return r0
}

// AssetRepository_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type AssetRepository_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AssetRepository_Expecter) Begin(ctx interface{}) *AssetRepository_Begin_Call {
	return &AssetRepository_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *AssetRepository_Begin_Call) Run(run func(ctx context.Context)) *AssetRepository_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AssetRepository_Begin_Call) Return(v shared.DB) *AssetRepository_Begin_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *AssetRepository_Begin_Call) RunAndReturn(run func(ctx context.Context) shared.DB) *AssetRepository_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type AssetRepository
func (_mock *AssetRepository) Create(ctx context.Context, tx shared.DB, t *models.Asset) error {
	ret := _mock.Called(ctx, tx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, *models.Asset) error); ok {
		r0 = returnFunc(ctx, tx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AssetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - t *models.Asset
func (_e *AssetRepository_Expecter) Create(ctx interface{}, tx interface{}, t interface{}) *AssetRepository_Create_Call {
	return &AssetRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, t)}
}

func (_c *AssetRepository_Create_Call) Run(run func(ctx context.Context, tx shared.DB, t *models.Asset)) *AssetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 *models.Asset
		if args[2] != nil {
			arg2 = args[2].(*models.Asset)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_Create_Call) Return(err error) *AssetRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssetRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, t *models.Asset) error) *AssetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function for the type AssetRepository
func (_mock *AssetRepository) CreateBatch(ctx context.Context, tx shared.DB, ts []models.Asset) error {
	ret := _mock.Called(ctx, tx, ts)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []models.Asset) error); ok {
		r0 = returnFunc(ctx, tx, ts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssetRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type AssetRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - ts []models.Asset
func (_e *AssetRepository_Expecter) CreateBatch(ctx interface{}, tx interface{}, ts interface{}) *AssetRepository_CreateBatch_Call {
	return &AssetRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, tx, ts)}
}

func (_c *AssetRepository_CreateBatch_Call) Run(run func(ctx context.Context, tx shared.DB, ts []models.Asset)) *AssetRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 []models.Asset
		if args[2] != nil {
			arg2 = args[2].([]models.Asset)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_CreateBatch_Call) Return(err error) *AssetRepository_CreateBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssetRepository_CreateBatch_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, ts []models.Asset) error) *AssetRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type AssetRepository
func (_mock *AssetRepository) Delete(ctx context.Context, tx shared.DB, id uuid.UUID) error {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssetRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AssetRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - id uuid.UUID
func (_e *AssetRepository_Expecter) Delete(ctx interface{}, tx interface{}, id interface{}) *AssetRepository_Delete_Call {
	return &AssetRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, tx, id)}
}

func (_c *AssetRepository_Delete_Call) Run(run func(ctx context.Context, tx shared.DB, id uuid.UUID)) *AssetRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_Delete_Call) Return(err error) *AssetRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssetRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, id uuid.UUID) error) *AssetRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBatch provides a mock function for the type AssetRepository
func (_mock *AssetRepository) DeleteBatch(ctx context.Context, tx shared.DB, ids []models.Asset) error {
	ret := _mock.Called(ctx, tx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []models.Asset) error); ok {
		r0 = returnFunc(ctx, tx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssetRepository_DeleteBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBatch'
type AssetRepository_DeleteBatch_Call struct {
	*mock.Call
}

// DeleteBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - ids []models.Asset
func (_e *AssetRepository_Expecter) DeleteBatch(ctx interface{}, tx interface{}, ids interface{}) *AssetRepository_DeleteBatch_Call {
	return &AssetRepository_DeleteBatch_Call{Call: _e.mock.On("DeleteBatch", ctx, tx, ids)}
}

func (_c *AssetRepository_DeleteBatch_Call) Run(run func(ctx context.Context, tx shared.DB, ids []models.Asset)) *AssetRepository_DeleteBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 []models.Asset
		if args[2] != nil {
			arg2 = args[2].([]models.Asset)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_DeleteBatch_Call) Return(err error) *AssetRepository_DeleteBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssetRepository_DeleteBatch_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, ids []models.Asset) error) *AssetRepository_DeleteBatch_Call {
	_c.Call.Return(run)
	return _c
}

// FindAssetByExternalProviderID provides a mock function for the type AssetRepository
func (_mock *AssetRepository) FindAssetByExternalProviderID(ctx context.Context, tx shared.DB, externalEntityProviderID string, externalEntityID string) (*models.Asset, error) {
	ret := _mock.Called(ctx, tx, externalEntityProviderID, externalEntityID)

	if len(ret) == 0 {
		panic("no return value specified for FindAssetByExternalProviderID")
	}

	var r0 *models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, string, string) (*models.Asset, error)); ok {
		return returnFunc(ctx, tx, externalEntityProviderID, externalEntityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, string, string) *models.Asset); ok {
		r0 = returnFunc(ctx, tx, externalEntityProviderID, externalEntityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Asset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, string, string) error); ok {
		r1 = returnFunc(ctx, tx, externalEntityProviderID, externalEntityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_FindAssetByExternalProviderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAssetByExternalProviderID'
type AssetRepository_FindAssetByExternalProviderID_Call struct {
	*mock.Call
}

// FindAssetByExternalProviderID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - externalEntityProviderID string
//   - externalEntityID string
func (_e *AssetRepository_Expecter) FindAssetByExternalProviderID(ctx interface{}, tx interface{}, externalEntityProviderID interface{}, externalEntityID interface{}) *AssetRepository_FindAssetByExternalProviderID_Call {
	return &AssetRepository_FindAssetByExternalProviderID_Call{Call: _e.mock.On("FindAssetByExternalProviderID", ctx, tx, externalEntityProviderID, externalEntityID)}
}

func (_c *AssetRepository_FindAssetByExternalProviderID_Call) Run(run func(ctx context.Context, tx shared.DB, externalEntityProviderID string, externalEntityID string)) *AssetRepository_FindAssetByExternalProviderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AssetRepository_FindAssetByExternalProviderID_Call) Return(asset *models.Asset, err error) *AssetRepository_FindAssetByExternalProviderID_Call {
	_c.Call.Return(asset, err)
	return _c
}

func (_c *AssetRepository_FindAssetByExternalProviderID_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, externalEntityProviderID string, externalEntityID string) (*models.Asset, error)) *AssetRepository_FindAssetByExternalProviderID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type AssetRepository
func (_mock *AssetRepository) FindByName(ctx context.Context, tx shared.DB, name string) (models.Asset, error) {
	ret := _mock.Called(ctx, tx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, string) (models.Asset, error)); ok {
		return returnFunc(ctx, tx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, string) models.Asset); ok {
		r0 = returnFunc(ctx, tx, name)
	} else {
		r0 = ret.Get(0).(models.Asset)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, string) error); ok {
		r1 = returnFunc(ctx, tx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type AssetRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - name string
func (_e *AssetRepository_Expecter) FindByName(ctx interface{}, tx interface{}, name interface{}) *AssetRepository_FindByName_Call {
	return &AssetRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, tx, name)}
}

func (_c *AssetRepository_FindByName_Call) Run(run func(ctx context.Context, tx shared.DB, name string)) *AssetRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_FindByName_Call) Return(asset models.Asset, err error) *AssetRepository_FindByName_Call {
	_c.Call.Return(asset, err)
	return _c
}

func (_c *AssetRepository_FindByName_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, name string) (models.Asset, error)) *AssetRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAssetsFromDB provides a mock function for the type AssetRepository
func (_mock *AssetRepository) GetAllAssetsFromDB(ctx context.Context, tx shared.DB) ([]models.Asset, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssetsFromDB")
	}

	var r0 []models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB) ([]models.Asset, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB) []models.Asset); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Asset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB) error); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_GetAllAssetsFromDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAssetsFromDB'
type AssetRepository_GetAllAssetsFromDB_Call struct {
	*mock.Call
}

// GetAllAssetsFromDB is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
func (_e *AssetRepository_Expecter) GetAllAssetsFromDB(ctx interface{}, tx interface{}) *AssetRepository_GetAllAssetsFromDB_Call {
	return &AssetRepository_GetAllAssetsFromDB_Call{Call: _e.mock.On("GetAllAssetsFromDB", ctx, tx)}
}

func (_c *AssetRepository_GetAllAssetsFromDB_Call) Run(run func(ctx context.Context, tx shared.DB)) *AssetRepository_GetAllAssetsFromDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AssetRepository_GetAllAssetsFromDB_Call) Return(assets []models.Asset, err error) *AssetRepository_GetAllAssetsFromDB_Call {
	_c.Call.Return(assets, err)
	return _c
}

func (_c *AssetRepository_GetAllAssetsFromDB_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB) ([]models.Asset, error)) *AssetRepository_GetAllAssetsFromDB_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllowedAssetsByProjectID provides a mock function for the type AssetRepository
func (_mock *AssetRepository) GetAllowedAssetsByProjectID(ctx context.Context, tx shared.DB, allowedAssetIDs []string, projectID uuid.UUID) ([]models.Asset, error) {
	ret := _mock.Called(ctx, tx, allowedAssetIDs, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllowedAssetsByProjectID")
	}

	var r0 []models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []string, uuid.UUID) ([]models.Asset, error)); ok {
		return returnFunc(ctx, tx, allowedAssetIDs, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []string, uuid.UUID) []models.Asset); ok {
		r0 = returnFunc(ctx, tx, allowedAssetIDs, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Asset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, []string, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, allowedAssetIDs, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_GetAllowedAssetsByProjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllowedAssetsByProjectID'
type AssetRepository_GetAllowedAssetsByProjectID_Call struct {
	*mock.Call
}

// GetAllowedAssetsByProjectID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - allowedAssetIDs []string
//   - projectID uuid.UUID
func (_e *AssetRepository_Expecter) GetAllowedAssetsByProjectID(ctx interface{}, tx interface{}, allowedAssetIDs interface{}, projectID interface{}) *AssetRepository_GetAllowedAssetsByProjectID_Call {
	return &AssetRepository_GetAllowedAssetsByProjectID_Call{Call: _e.mock.On("GetAllowedAssetsByProjectID", ctx, tx, allowedAssetIDs, projectID)}
}

func (_c *AssetRepository_GetAllowedAssetsByProjectID_Call) Run(run func(ctx context.Context, tx shared.DB, allowedAssetIDs []string, projectID uuid.UUID)) *AssetRepository_GetAllowedAssetsByProjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AssetRepository_GetAllowedAssetsByProjectID_Call) Return(assets []models.Asset, err error) *AssetRepository_GetAllowedAssetsByProjectID_Call {
	_c.Call.Return(assets, err)
	return _c
}

func (_c *AssetRepository_GetAllowedAssetsByProjectID_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, allowedAssetIDs []string, projectID uuid.UUID) ([]models.Asset, error)) *AssetRepository_GetAllowedAssetsByProjectID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssetIDBySlug provides a mock function for the type AssetRepository
func (_mock *AssetRepository) GetAssetIDBySlug(ctx context.Context, tx shared.DB, projectID uuid.UUID, slug string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, tx, projectID, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetIDBySlug")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, tx, projectID, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, tx, projectID, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, tx, projectID, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_GetAssetIDBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssetIDBySlug'
type AssetRepository_GetAssetIDBySlug_Call struct {
	*mock.Call
}

// GetAssetIDBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - projectID uuid.UUID
//   - slug string
func (_e *AssetRepository_Expecter) GetAssetIDBySlug(ctx interface{}, tx interface{}, projectID interface{}, slug interface{}) *AssetRepository_GetAssetIDBySlug_Call {
	return &AssetRepository_GetAssetIDBySlug_Call{Call: _e.mock.On("GetAssetIDBySlug", ctx, tx, projectID, slug)}
}

func (_c *AssetRepository_GetAssetIDBySlug_Call) Run(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID, slug string)) *AssetRepository_GetAssetIDBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AssetRepository_GetAssetIDBySlug_Call) Return(uUID uuid.UUID, err error) *AssetRepository_GetAssetIDBySlug_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *AssetRepository_GetAssetIDBySlug_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID, slug string) (uuid.UUID, error)) *AssetRepository_GetAssetIDBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssetsWithVulnSharingEnabled provides a mock function for the type AssetRepository
func (_mock *AssetRepository) GetAssetsWithVulnSharingEnabled(ctx context.Context, tx shared.DB, orgID uuid.UUID) ([]models.Asset, error) {
	ret := _mock.Called(ctx, tx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetsWithVulnSharingEnabled")
	}

	var r0 []models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) ([]models.Asset, error)); ok {
		return returnFunc(ctx, tx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) []models.Asset); ok {
		r0 = returnFunc(ctx, tx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Asset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_GetAssetsWithVulnSharingEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssetsWithVulnSharingEnabled'
type AssetRepository_GetAssetsWithVulnSharingEnabled_Call struct {
	*mock.Call
}

// GetAssetsWithVulnSharingEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - orgID uuid.UUID
func (_e *AssetRepository_Expecter) GetAssetsWithVulnSharingEnabled(ctx interface{}, tx interface{}, orgID interface{}) *AssetRepository_GetAssetsWithVulnSharingEnabled_Call {
	return &AssetRepository_GetAssetsWithVulnSharingEnabled_Call{Call: _e.mock.On("GetAssetsWithVulnSharingEnabled", ctx, tx, orgID)}
}

func (_c *AssetRepository_GetAssetsWithVulnSharingEnabled_Call) Run(run func(ctx context.Context, tx shared.DB, orgID uuid.UUID)) *AssetRepository_GetAssetsWithVulnSharingEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_GetAssetsWithVulnSharingEnabled_Call) Return(assets []models.Asset, err error) *AssetRepository_GetAssetsWithVulnSharingEnabled_Call {
	_c.Call.Return(assets, err)
	return _c
}

func (_c *AssetRepository_GetAssetsWithVulnSharingEnabled_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, orgID uuid.UUID) ([]models.Asset, error)) *AssetRepository_GetAssetsWithVulnSharingEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOrgID provides a mock function for the type AssetRepository
func (_mock *AssetRepository) GetByOrgID(ctx context.Context, tx shared.DB, organizationID uuid.UUID) ([]models.Asset, error) {
	ret := _mock.Called(ctx, tx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrgID")
	}

	var r0 []models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) ([]models.Asset, error)); ok {
		return returnFunc(ctx, tx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) []models.Asset); ok {
		r0 = returnFunc(ctx, tx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Asset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_GetByOrgID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOrgID'
type AssetRepository_GetByOrgID_Call struct {
	*mock.Call
}

// GetByOrgID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - organizationID uuid.UUID
func (_e *AssetRepository_Expecter) GetByOrgID(ctx interface{}, tx interface{}, organizationID interface{}) *AssetRepository_GetByOrgID_Call {
	return &AssetRepository_GetByOrgID_Call{Call: _e.mock.On("GetByOrgID", ctx, tx, organizationID)}
}

func (_c *AssetRepository_GetByOrgID_Call) Run(run func(ctx context.Context, tx shared.DB, organizationID uuid.UUID)) *AssetRepository_GetByOrgID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_GetByOrgID_Call) Return(assets []models.Asset, err error) *AssetRepository_GetByOrgID_Call {
	_c.Call.Return(assets, err)
	return _c
}

func (_c *AssetRepository_GetByOrgID_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, organizationID uuid.UUID) ([]models.Asset, error)) *AssetRepository_GetByOrgID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProjectID provides a mock function for the type AssetRepository
func (_mock *AssetRepository) GetByProjectID(ctx context.Context, tx shared.DB, projectID uuid.UUID) ([]models.Asset, error) {
	ret := _mock.Called(ctx, tx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProjectID")
	}

	var r0 []models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) ([]models.Asset, error)); ok {
		return returnFunc(ctx, tx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) []models.Asset); ok {
		r0 = returnFunc(ctx, tx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Asset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_GetByProjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProjectID'
type AssetRepository_GetByProjectID_Call struct {
	*mock.Call
}

// GetByProjectID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - projectID uuid.UUID
func (_e *AssetRepository_Expecter) GetByProjectID(ctx interface{}, tx interface{}, projectID interface{}) *AssetRepository_GetByProjectID_Call {
	return &AssetRepository_GetByProjectID_Call{Call: _e.mock.On("GetByProjectID", ctx, tx, projectID)}
}

func (_c *AssetRepository_GetByProjectID_Call) Run(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID)) *AssetRepository_GetByProjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_GetByProjectID_Call) Return(assets []models.Asset, err error) *AssetRepository_GetByProjectID_Call {
	_c.Call.Return(assets, err)
	return _c
}

func (_c *AssetRepository_GetByProjectID_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID) ([]models.Asset, error)) *AssetRepository_GetByProjectID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDB provides a mock function for the type AssetRepository
func (_mock *AssetRepository) GetDB(ctx context.Context, tx shared.DB) shared.DB {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 shared.DB
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB) shared.DB); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.DB)
		}
	}
	return r0
}

// AssetRepository_GetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDB'
type AssetRepository_GetDB_Call struct {
	*mock.Call
}

// GetDB is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
func (_e *AssetRepository_Expecter) GetDB(ctx interface{}, tx interface{}) *AssetRepository_GetDB_Call {
	return &AssetRepository_GetDB_Call{Call: _e.mock.On("GetDB", ctx, tx)}
}

func (_c *AssetRepository_GetDB_Call) Run(run func(ctx context.Context, tx shared.DB)) *AssetRepository_GetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AssetRepository_GetDB_Call) Return(v shared.DB) *AssetRepository_GetDB_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *AssetRepository_GetDB_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB) shared.DB) *AssetRepository_GetDB_Call {
	_c.Call.Return(run)
	return _c
}

// GetFQNByID provides a mock function for the type AssetRepository
func (_mock *AssetRepository) GetFQNByID(ctx context.Context, tx shared.DB, id uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFQNByID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_GetFQNByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFQNByID'
type AssetRepository_GetFQNByID_Call struct {
	*mock.Call
}

// GetFQNByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - id uuid.UUID
func (_e *AssetRepository_Expecter) GetFQNByID(ctx interface{}, tx interface{}, id interface{}) *AssetRepository_GetFQNByID_Call {
	return &AssetRepository_GetFQNByID_Call{Call: _e.mock.On("GetFQNByID", ctx, tx, id)}
}

func (_c *AssetRepository_GetFQNByID_Call) Run(run func(ctx context.Context, tx shared.DB, id uuid.UUID)) *AssetRepository_GetFQNByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_GetFQNByID_Call) Return(s string, err error) *AssetRepository_GetFQNByID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AssetRepository_GetFQNByID_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, id uuid.UUID) (string, error)) *AssetRepository_GetFQNByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type AssetRepository
func (_mock *AssetRepository) List(ctx context.Context, tx shared.DB, ids []uuid.UUID) ([]models.Asset, error) {
	ret := _mock.Called(ctx, tx, ids)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []uuid.UUID) ([]models.Asset, error)); ok {
		return returnFunc(ctx, tx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []uuid.UUID) []models.Asset); ok {
		r0 = returnFunc(ctx, tx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Asset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type AssetRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - ids []uuid.UUID
func (_e *AssetRepository_Expecter) List(ctx interface{}, tx interface{}, ids interface{}) *AssetRepository_List_Call {
	return &AssetRepository_List_Call{Call: _e.mock.On("List", ctx, tx, ids)}
}

func (_c *AssetRepository_List_Call) Run(run func(ctx context.Context, tx shared.DB, ids []uuid.UUID)) *AssetRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_List_Call) Return(assets []models.Asset, err error) *AssetRepository_List_Call {
	_c.Call.Return(assets, err)
	return _c
}

func (_c *AssetRepository_List_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, ids []uuid.UUID) ([]models.Asset, error)) *AssetRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type AssetRepository
func (_mock *AssetRepository) Read(ctx context.Context, tx shared.DB, id uuid.UUID) (models.Asset, error) {
	ret := _mock.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) (models.Asset, error)); ok {
		return returnFunc(ctx, tx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) models.Asset); ok {
		r0 = returnFunc(ctx, tx, id)
	} else {
		r0 = ret.Get(0).(models.Asset)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type AssetRepository_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - id uuid.UUID
func (_e *AssetRepository_Expecter) Read(ctx interface{}, tx interface{}, id interface{}) *AssetRepository_Read_Call {
	return &AssetRepository_Read_Call{Call: _e.mock.On("Read", ctx, tx, id)}
}

func (_c *AssetRepository_Read_Call) Run(run func(ctx context.Context, tx shared.DB, id uuid.UUID)) *AssetRepository_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_Read_Call) Return(asset models.Asset, err error) *AssetRepository_Read_Call {
	_c.Call.Return(asset, err)
	return _c
}

func (_c *AssetRepository_Read_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, id uuid.UUID) (models.Asset, error)) *AssetRepository_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadBySlug provides a mock function for the type AssetRepository
func (_mock *AssetRepository) ReadBySlug(ctx context.Context, tx shared.DB, projectID uuid.UUID, slug string) (models.Asset, error) {
	ret := _mock.Called(ctx, tx, projectID, slug)

	if len(ret) == 0 {
		panic("no return value specified for ReadBySlug")
	}

	var r0 models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID, string) (models.Asset, error)); ok {
		return returnFunc(ctx, tx, projectID, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID, string) models.Asset); ok {
		r0 = returnFunc(ctx, tx, projectID, slug)
	} else {
		r0 = ret.Get(0).(models.Asset)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, tx, projectID, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_ReadBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBySlug'
type AssetRepository_ReadBySlug_Call struct {
	*mock.Call
}

// ReadBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - projectID uuid.UUID
//   - slug string
func (_e *AssetRepository_Expecter) ReadBySlug(ctx interface{}, tx interface{}, projectID interface{}, slug interface{}) *AssetRepository_ReadBySlug_Call {
	return &AssetRepository_ReadBySlug_Call{Call: _e.mock.On("ReadBySlug", ctx, tx, projectID, slug)}
}

func (_c *AssetRepository_ReadBySlug_Call) Run(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID, slug string)) *AssetRepository_ReadBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AssetRepository_ReadBySlug_Call) Return(asset models.Asset, err error) *AssetRepository_ReadBySlug_Call {
	_c.Call.Return(asset, err)
	return _c
}

func (_c *AssetRepository_ReadBySlug_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID, slug string) (models.Asset, error)) *AssetRepository_ReadBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// ReadBySlugUnscoped provides a mock function for the type AssetRepository
func (_mock *AssetRepository) ReadBySlugUnscoped(ctx context.Context, tx shared.DB, projectID uuid.UUID, slug string) (models.Asset, error) {
	ret := _mock.Called(ctx, tx, projectID, slug)

	if len(ret) == 0 {
		panic("no return value specified for ReadBySlugUnscoped")
	}

	var r0 models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID, string) (models.Asset, error)); ok {
		return returnFunc(ctx, tx, projectID, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID, string) models.Asset); ok {
		r0 = returnFunc(ctx, tx, projectID, slug)
	} else {
		r0 = ret.Get(0).(models.Asset)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, tx, projectID, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_ReadBySlugUnscoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBySlugUnscoped'
type AssetRepository_ReadBySlugUnscoped_Call struct {
	*mock.Call
}

// ReadBySlugUnscoped is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - projectID uuid.UUID
//   - slug string
func (_e *AssetRepository_Expecter) ReadBySlugUnscoped(ctx interface{}, tx interface{}, projectID interface{}, slug interface{}) *AssetRepository_ReadBySlugUnscoped_Call {
	return &AssetRepository_ReadBySlugUnscoped_Call{Call: _e.mock.On("ReadBySlugUnscoped", ctx, tx, projectID, slug)}
}

func (_c *AssetRepository_ReadBySlugUnscoped_Call) Run(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID, slug string)) *AssetRepository_ReadBySlugUnscoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AssetRepository_ReadBySlugUnscoped_Call) Return(asset models.Asset, err error) *AssetRepository_ReadBySlugUnscoped_Call {
	_c.Call.Return(asset, err)
	return _c
}

func (_c *AssetRepository_ReadBySlugUnscoped_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, projectID uuid.UUID, slug string) (models.Asset, error)) *AssetRepository_ReadBySlugUnscoped_Call {
	_c.Call.Return(run)
	return _c
}

// ReadWithAssetVersions provides a mock function for the type AssetRepository
func (_mock *AssetRepository) ReadWithAssetVersions(ctx context.Context, tx shared.DB, assetID uuid.UUID) (models.Asset, error) {
	ret := _mock.Called(ctx, tx, assetID)

	if len(ret) == 0 {
		panic("no return value specified for ReadWithAssetVersions")
	}

	var r0 models.Asset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) (models.Asset, error)); ok {
		return returnFunc(ctx, tx, assetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, uuid.UUID) models.Asset); ok {
		r0 = returnFunc(ctx, tx, assetID)
	} else {
		r0 = ret.Get(0).(models.Asset)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, shared.DB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tx, assetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AssetRepository_ReadWithAssetVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadWithAssetVersions'
type AssetRepository_ReadWithAssetVersions_Call struct {
	*mock.Call
}

// ReadWithAssetVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - assetID uuid.UUID
func (_e *AssetRepository_Expecter) ReadWithAssetVersions(ctx interface{}, tx interface{}, assetID interface{}) *AssetRepository_ReadWithAssetVersions_Call {
	return &AssetRepository_ReadWithAssetVersions_Call{Call: _e.mock.On("ReadWithAssetVersions", ctx, tx, assetID)}
}

func (_c *AssetRepository_ReadWithAssetVersions_Call) Run(run func(ctx context.Context, tx shared.DB, assetID uuid.UUID)) *AssetRepository_ReadWithAssetVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_ReadWithAssetVersions_Call) Return(asset models.Asset, err error) *AssetRepository_ReadWithAssetVersions_Call {
	_c.Call.Return(asset, err)
	return _c
}

func (_c *AssetRepository_ReadWithAssetVersions_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, assetID uuid.UUID) (models.Asset, error)) *AssetRepository_ReadWithAssetVersions_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type AssetRepository
func (_mock *AssetRepository) Save(ctx context.Context, tx shared.DB, t *models.Asset) error {
	ret := _mock.Called(ctx, tx, t)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, *models.Asset) error); ok {
		r0 = returnFunc(ctx, tx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssetRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type AssetRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - t *models.Asset
func (_e *AssetRepository_Expecter) Save(ctx interface{}, tx interface{}, t interface{}) *AssetRepository_Save_Call {
	return &AssetRepository_Save_Call{Call: _e.mock.On("Save", ctx, tx, t)}
}

func (_c *AssetRepository_Save_Call) Run(run func(ctx context.Context, tx shared.DB, t *models.Asset)) *AssetRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 *models.Asset
		if args[2] != nil {
			arg2 = args[2].(*models.Asset)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_Save_Call) Return(err error) *AssetRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssetRepository_Save_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, t *models.Asset) error) *AssetRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatch provides a mock function for the type AssetRepository
func (_mock *AssetRepository) SaveBatch(ctx context.Context, tx shared.DB, ts []models.Asset) error {
	ret := _mock.Called(ctx, tx, ts)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []models.Asset) error); ok {
		r0 = returnFunc(ctx, tx, ts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssetRepository_SaveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatch'
type AssetRepository_SaveBatch_Call struct {
	*mock.Call
}

// SaveBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - ts []models.Asset
func (_e *AssetRepository_Expecter) SaveBatch(ctx interface{}, tx interface{}, ts interface{}) *AssetRepository_SaveBatch_Call {
	return &AssetRepository_SaveBatch_Call{Call: _e.mock.On("SaveBatch", ctx, tx, ts)}
}

func (_c *AssetRepository_SaveBatch_Call) Run(run func(ctx context.Context, tx shared.DB, ts []models.Asset)) *AssetRepository_SaveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 []models.Asset
		if args[2] != nil {
			arg2 = args[2].([]models.Asset)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_SaveBatch_Call) Return(err error) *AssetRepository_SaveBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssetRepository_SaveBatch_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, ts []models.Asset) error) *AssetRepository_SaveBatch_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBatchBestEffort provides a mock function for the type AssetRepository
func (_mock *AssetRepository) SaveBatchBestEffort(ctx context.Context, tx shared.DB, ts []models.Asset) error {
	ret := _mock.Called(ctx, tx, ts)

	if len(ret) == 0 {
		panic("no return value specified for SaveBatchBestEffort")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, []models.Asset) error); ok {
		r0 = returnFunc(ctx, tx, ts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssetRepository_SaveBatchBestEffort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBatchBestEffort'
type AssetRepository_SaveBatchBestEffort_Call struct {
	*mock.Call
}

// SaveBatchBestEffort is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - ts []models.Asset
func (_e *AssetRepository_Expecter) SaveBatchBestEffort(ctx interface{}, tx interface{}, ts interface{}) *AssetRepository_SaveBatchBestEffort_Call {
	return &AssetRepository_SaveBatchBestEffort_Call{Call: _e.mock.On("SaveBatchBestEffort", ctx, tx, ts)}
}

func (_c *AssetRepository_SaveBatchBestEffort_Call) Run(run func(ctx context.Context, tx shared.DB, ts []models.Asset)) *AssetRepository_SaveBatchBestEffort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 []models.Asset
		if args[2] != nil {
			arg2 = args[2].([]models.Asset)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_SaveBatchBestEffort_Call) Return(err error) *AssetRepository_SaveBatchBestEffort_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssetRepository_SaveBatchBestEffort_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, ts []models.Asset) error) *AssetRepository_SaveBatchBestEffort_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function for the type AssetRepository
func (_mock *AssetRepository) Transaction(ctx context.Context, fn func(tx shared.DB) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx shared.DB) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssetRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type AssetRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx shared.DB) error
func (_e *AssetRepository_Expecter) Transaction(ctx interface{}, fn interface{}) *AssetRepository_Transaction_Call {
	return &AssetRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *AssetRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(tx shared.DB) error)) *AssetRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx shared.DB) error
		if args[1] != nil {
			arg1 = args[1].(func(tx shared.DB) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AssetRepository_Transaction_Call) Return(err error) *AssetRepository_Transaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssetRepository_Transaction_Call) RunAndReturn(run func(ctx context.Context, fn func(tx shared.DB) error) error) *AssetRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type AssetRepository
func (_mock *AssetRepository) Update(ctx context.Context, tx shared.DB, asset *models.Asset) error {
	ret := _mock.Called(ctx, tx, asset)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, *models.Asset) error); ok {
		r0 = returnFunc(ctx, tx, asset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssetRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type AssetRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - asset *models.Asset
func (_e *AssetRepository_Expecter) Update(ctx interface{}, tx interface{}, asset interface{}) *AssetRepository_Update_Call {
	return &AssetRepository_Update_Call{Call: _e.mock.On("Update", ctx, tx, asset)}
}

func (_c *AssetRepository_Update_Call) Run(run func(ctx context.Context, tx shared.DB, asset *models.Asset)) *AssetRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 *models.Asset
		if args[2] != nil {
			arg2 = args[2].(*models.Asset)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AssetRepository_Update_Call) Return(err error) *AssetRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssetRepository_Update_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, asset *models.Asset) error) *AssetRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type AssetRepository
func (_mock *AssetRepository) Upsert(ctx context.Context, tx shared.DB, t *[]*models.Asset, conflictingColumns []clause.Column, updateOnly []string) error {
	ret := _mock.Called(ctx, tx, t, conflictingColumns, updateOnly)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, shared.DB, *[]*models.Asset, []clause.Column, []string) error); ok {
		r0 = returnFunc(ctx, tx, t, conflictingColumns, updateOnly)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssetRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type AssetRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - tx shared.DB
//   - t *[]*models.Asset
//   - conflictingColumns []clause.Column
//   - updateOnly []string
func (_e *AssetRepository_Expecter) Upsert(ctx interface{}, tx interface{}, t interface{}, conflictingColumns interface{}, updateOnly interface{}) *AssetRepository_Upsert_Call {
	return &AssetRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, tx, t, conflictingColumns, updateOnly)}
}

func (_c *AssetRepository_Upsert_Call) Run(run func(ctx context.Context, tx shared.DB, t *[]*models.Asset, conflictingColumns []clause.Column, updateOnly []string)) *AssetRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 shared.DB
		if args[1] != nil {
			arg1 = args[1].(shared.DB)
		}
		var arg2 *[]*models.Asset
		if args[2] != nil {
			arg2 = args[2].(*[]*models.Asset)
		}
		var arg3 []clause.Column
		if args[3] != nil {
			arg3 = args[3].([]clause.Column)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AssetRepository_Upsert_Call) Return(err error) *AssetRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssetRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, tx shared.DB, t *[]*models.Asset, conflictingColumns []clause.Column, updateOnly []string) error) *AssetRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
