-- Add risk distribution columns to asset_risk_history table
ALTER TABLE public.asset_risk_history 
ADD COLUMN IF NOT EXISTS low INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS medium INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS high INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS critical INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS low_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS medium_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS high_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS critical_cvss INTEGER DEFAULT 0;

-- Add risk distribution columns to project_risk_history table
ALTER TABLE public.project_risk_history 
ADD COLUMN IF NOT EXISTS low INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS medium INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS high INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS critical INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS low_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS medium_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS high_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS critical_cvss INTEGER DEFAULT 0;
