ALTER TABLE public.pat ADD COLUMN IF NOT EXISTS bearer_token_hash TEXT NULL DEFAULT NULL;
ALTER TABLE public.pat ALTER COLUMN fingerprint DROP NOT NULL;
ALTER TABLE public.pat ALTER COLUMN pub_key DROP NOT NULL;