ALTER TABLE public.artifact_risk_history
ADD COLUMN IF NOT EXISTS unique_low INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_medium INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_high INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_critical INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_low_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_medium_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_high_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_critical_cvss INTEGER DEFAULT 0;

ALTER TABLE public.project_risk_history
ADD COLUMN IF NOT EXISTS unique_low INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_medium INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_high INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_critical INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_low_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_medium_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_high_cvss INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unique_critical_cvss INTEGER DEFAULT 0;
