ALTER TABLE public.artifact_risk_history
ADD COLUMN IF NOT EXISTS fixable_low INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS fixable_medium INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS fixable_high INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS fixable_critical INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS cve_purl_fixable_low INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS cve_purl_fixable_medium INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS cve_purl_fixable_high INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS cve_purl_fixable_critical INTEGER DEFAULT 0;

