// Copyright (C) 2026 l3montree GmbH
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package commands

import (
	"fmt"
	"io"
	"log/slog"
	"os"

	"github.com/l3montree-dev/devguard/cmd/devguard-scanner/scanner"
	"github.com/spf13/cobra"
)

// workloadIdentityTokenEnv is the variable name the GitLab id_tokens keyword should use for the devguard token
const workloadIdentityTokenEnv = "DEVGUARD_ID_TOKEN"

func signProvenanceCmd(cmd *cobra.Command, args []string) error {
	idToken, err := cmd.Flags().GetString("idToken")
	if err != nil {
		return err
	}
	if idToken == "" {
		idToken = os.Getenv(workloadIdentityTokenEnv)
	}
	if idToken == "" {
		return fmt.Errorf("no workload identity token provided. Use --idToken or request one in your CI job with the audience of the devguard api and expose it as %s", workloadIdentityTokenEnv)
	}

	var statement []byte
	if args[0] == "-" {
		statement, err = io.ReadAll(os.Stdin)
	} else {
		statement, err = os.ReadFile(args[0])
	}
	if err != nil {
		return fmt.Errorf("could not read provenance: %w", err)
	}

	signed, err := scanner.SignBuildProvenance(cmd.Context(), statement, idToken)
	if err != nil {
		return err
	}

	output, err := cmd.Flags().GetString("output")
	if err != nil {
		return err
	}
	if output == "" || output == "-" {
		_, err = os.Stdout.Write(signed)
		return err
	}
	if err := os.WriteFile(output, signed, 0644); err != nil {
		return fmt.Errorf("could not write signed provenance: %w", err)
	}
	slog.Info("signed build provenance", "output", output)
	return nil
}

func newSignProvenanceCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "sign <provenance>",
		Short:             "Let DevGuard sign SLSA build provenance with the verified identity of the CI job",
		DisableAutoGenTag: true,
		Long: `Send an in-toto statement with a SLSA v1 provenance predicate to DevGuard for signing.

DevGuard verifies the OIDC workload identity token of the CI job with its issuer and writes the
verified identity into the provenance before signing it:

  predicate.runDetails.builder.id                                         the ci config which ran the build, including the issuer
  predicate.buildDefinition.internalParameters.devguard.workloadIdentity  all claims of the verified token

Every field describing who built the artifact is overwritten. Subjects and the build description
are kept as sent.

The token must be issued for the audience of the DevGuard API. In GitLab request it with:

  id_tokens:
    DEVGUARD_ID_TOKEN:
      aud: https://api.devguard.org

The result is a DSSE envelope - or a sigstore bundle, if DevGuard uploads to a transparency log.
Pass it to 'devguard-scanner attest' to attach it to an image: already signed input is attached as-is.
The first argument is a path to the provenance JSON file. Pass "-" to read from stdin.`,
		Example: `  # Sign the provenance generated by 'devguard-scanner intoto stop --generateSlsaProvenance'
  devguard-scanner provenance sign build.provenance.json --output build.provenance.dsse.json --token=$DEVGUARD_TOKEN --assetName=$DEVGUARD_ASSET_NAME

  # Attach the signed provenance to the image without signing it again
  devguard-scanner attest build.provenance.dsse.json ghcr.io/org/image:tag --predicateType https://slsa.dev/provenance/v1

  # Pass the token explicitly and print the signed provenance to stdout
  devguard-scanner provenance sign build.provenance.json --idToken="$MY_ID_TOKEN"`,
		Args: cobra.ExactArgs(1),
		RunE: signProvenanceCmd,
		Annotations: map[string]string{
			"title":           "DevGuard-Scanner provenance sign — Sign SLSA build provenance",
			"description":     "Let DevGuard sign SLSA build provenance and embed the verified OIDC workload identity of the CI job with devguard-scanner provenance sign.",
			"keyword_primary": "devguard-scanner provenance sign",
		},
	}

	scanner.AddDefaultFlags(cmd)
	scanner.AddAssetRefFlags(cmd)
	cmd.Flags().String("idToken", "", "The OIDC workload identity token of the CI job. Defaults to the "+workloadIdentityTokenEnv+" environment variable.")
	cmd.Flags().StringP("output", "o", "", "File to write the signed provenance to. Defaults to stdout.")
	return cmd
}

func NewProvenanceCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "provenance",
		Short:             "Work with SLSA build provenance",
		DisableAutoGenTag: true,
		Annotations: map[string]string{
			"title":           "DevGuard-Scanner provenance — Work with SLSA build provenance",
			"description":     "Sign SLSA build provenance with DevGuard as build control plane using devguard-scanner provenance.",
			"keyword_primary": "devguard-scanner provenance",
		},
	}
	cmd.AddCommand(newSignProvenanceCommand())
	return cmd
}
