name: DevGuard PostgreSQL Workflow

on:
  push:

jobs:
  postgresql-pipeline:
    uses: l3montree-dev/devguard-action/.github/workflows/container-lifecycle-nix.yml@nix
    permissions:
      contents: read
      packages: write
    with:
      nix-target: devguardPostgresqlOCI
      image-name: ghcr.io/${{ github.repository }}/postgresql
      artifact-name-suffix: postgresql
      asset-name: l3montree-cybersecurity/projects/devguard/assets/devguard-postgresql
      api-url: https://api.main.devguard.org
      web-ui: https://main.devguard.org
      fail-on-cvss: high
      fail-on-risk: high
    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
